<?php

namespace AppBundle\Repository\CrepRepository\CrepMso3Repository;

/**
 * CrepSclRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMso3Repository extends \Doctrine\ORM\EntityRepository
{
}
