<?php

namespace AppBundle\Repository\CrepRepository\CrepMj01Repository;

/**
 * CrepMj01Repository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMj01Repository extends \Doctrine\ORM\EntityRepository
{
}
