<?php

namespace AppBundle\Repository\CrepRepository\CrepMindefRepository;

/**
 * CrepMindefRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMindefRepository extends \Doctrine\ORM\EntityRepository
{
}
