<?php

namespace AppBundle\Repository\CrepRepository\CrepMindefRepository;

/**
 * CrepMindefCompetenceTransverseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMindefCompetenceTransverseRepository extends \Doctrine\ORM\EntityRepository
{
}
