<?php

namespace AppBundle\Repository\CrepRepository\CrepEddRepository;

/**
 * ContraintePosteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepEddContraintePosteRepository extends \Doctrine\ORM\EntityRepository
{
}
