<?php

namespace AppBundle\Repository\CrepRepository\CrepEddRepository;

/**
 * CrepEddRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepEdd2Repository extends \Doctrine\ORM\EntityRepository
{
}
