<?php

namespace AppBundle\Repository\CrepRepository\CrepEddMindefRepository;

/**
 * CrepEddMindefRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepEddMindefRepository extends \Doctrine\ORM\EntityRepository
{
}
