<?php

namespace AppBundle\Repository\RepriseMINDEF2016;

/**
 * FormationAVenir2016Repository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationAVenir2016Repository extends \Doctrine\ORM\EntityRepository
{
}
