<?php

namespace AppBundle\Repository\RepriseMINDEF2016;

/**
 * ObjectifFutur2016Repository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifFutur2016Repository extends \Doctrine\ORM\EntityRepository
{
}
