<?php

namespace AppBundle\Repository\Statistiques;

use AppBundle\Entity\CampagneBrhp;

/**
 * StatCampagneBrhpRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatCampagneBrhpRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHistoriqueIndicateurs(CampagneBrhp $campagneBrhp)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.campagneBrhp = :CAMPAGNE_BRHP')
        ->setParameter('CAMPAGNE_BRHP', $campagneBrhp)
        ->orderBy('s.dateStat');

        return $qb->getQuery()->getResult();
    }
}
