<?php

namespace AppBundle\Repository\Statistiques;

use AppBundle\Entity\CampagneRlc;

/**
 * StatCampagneRlcRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatCampagneRlcRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHistoriqueIndicateurs(CampagneRlc $campagneRlc)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.campagneRlc = :CAMPAGNE_RLC')
        ->setParameter('CAMPAGNE_RLC', $campagneRlc)
        ->orderBy('s.dateStat');

        return $qb->getQuery()->getResult();
    }
}
