<?php

namespace AppBundle\Repository\CrepRepository\CrepSclRepository;

/**
 * CrepSclRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepSclRepository extends \Doctrine\ORM\EntityRepository
{
}
