<?php

namespace AppBundle\Repository\CrepRepository\CrepSclRepository;

/**
 * CrepSclCompetenceTransverseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepSclCompetenceTransverseRepository extends \Doctrine\ORM\EntityRepository
{
}
