<?php

namespace AppBundle\Repository\CrepRepository\CrepDgacRepository;

/**
 * CrepDgacAutreCompetenceProfessionnelleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepDgacAutreCompetenceManagerialeRepository extends \Doctrine\ORM\EntityRepository
{
}
