<?php

namespace AppBundle\Repository;

/**
 * AgentImportRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentImportRepository extends \Doctrine\ORM\EntityRepository
{
}
