<?php

namespace AppBundle\Repository;

/**
 * BrhpConsultRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrhpConsultRepository extends \Doctrine\ORM\EntityRepository
{
}
