<?php

namespace AppBundle\Repository;

/**
 * BrhpRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrhpRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBrhpByEmail($email)
    {
        return $this->findOneByEmail($email);
    }
}
