<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ministere;

/**
 * CampagnePncRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagnePncRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupére les campagnes Pnc d'un ministère.
     *
     * @param Ministere $ministere Le ministère
     *
     * @return array
     */
    public function recupereCampagnesPncMinistere(Ministere $ministere)
    {
        return $this->findBy(array('ministere' => $ministere));
    }

    /**
     * Renvoie les $max campagne récentes.
     *
     * @param int $max
     *
     * @return array
     */
    public function findCampagnesRecentes($max)
    {
        $resultat = $this->findBy(array(), array('anneeEvaluee' => 'desc', 'libelle' => 'asc'));
        $resultat = array_slice($resultat, 0, $max);

        return $resultat;
    }
}
