<?php

namespace AppBundle\Repository;

/**
 * CompetenceDeclareeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceDeclareeRepository extends \Doctrine\ORM\EntityRepository
{
}
