<?php

namespace AppBundle\Repository;

/**
 * CompetencePosteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetencePosteRepository extends \Doctrine\ORM\EntityRepository
{
}
