<?php

namespace AppBundle\Repository;

/**
 * CompetenceManagerialeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceManagerialeRepository extends \Doctrine\ORM\EntityRepository
{
}
