<?php

namespace AppBundle\Repository;

/**
 * CompetenceTransverseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceTransverseRepository extends \Doctrine\ORM\EntityRepository
{
}
