<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Utilisateur;

/**
 * ConnexionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnexionRepository extends EntityRepository
{
    public function derniereConnexionUtilisateurs(Utilisateur $utilisateur, $max = 10)
    {
        $qb = $this->createQueryBuilder('c')
        ->where('c.utilisateur = :utilisateur')
        ->orderBy('c.dateConnexion', 'DESC')
        ->setParameter('utilisateur', $utilisateur);

        return array_slice($qb->getQuery()->getResult(), 0, $max);
    }
}
