<?php

namespace AppBundle\Repository;

/**
 * ContraintePosteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContraintePosteRepository extends \Doctrine\ORM\EntityRepository
{
}
