<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function getDocumentsAPurger()
    {
        $now = new \DateTime();
        $datePurge = $now->sub(new \DateInterval('PT1H'));

        $qb = $this->createQueryBuilder('d');
        $qb->where('d.brouillon = 1');
        $qb->andWhere('d.dateCreation < :datePurge');
        $qb->setParameter('datePurge', $datePurge);

        return $qb->getQuery()->getResult();
    }

    public function findOneDocumentBy($id, $checksum)
    {
        $qb = $this->createQueryBuilder('d')
        ->where('d.id = :ID')
        ->andWhere('d.checksum LIKE :CHECKSUM')
        ->setParameter('ID', $id)
        ->setParameter('CHECKSUM', $checksum);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findOneDocumentByChecksum($checksum)
    {
        $qb = $this->createQueryBuilder('d')
        ->where('d.checksum LIKE :CHECKSUM')
        ->setParameter('CHECKSUM', $checksum);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
