<?php

namespace AppBundle\Repository;

/**
 * EvolutionProfessionnelleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolutionProfessionnelleRepository extends \Doctrine\ORM\EntityRepository
{
}
