<?php

namespace AppBundle\Repository;

/**
 * FormationDemandeeEmployeurRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationDemandeeEmployeurRepository extends \Doctrine\ORM\EntityRepository
{
}
