<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Utilisateur;

/**
 * MessageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getMessagesUtilisateur(Utilisateur $utilisateur)
    {
        $qb = $this->createQueryBuilder('m')
        ->where('m.destinataire = :DESTINATAIRE')
        ->andWhere('m.supprime = 0')
        ->setParameter('DESTINATAIRE', $utilisateur);
        //->orderBy('m.dateEnvoi','DESC')
        //->addOrderBy('m.id', 'DESC');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
