<?php

namespace AppBundle\Repository;

/**
 * MobiliteFonctionnelleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobiliteFonctionnelleRepository extends \Doctrine\ORM\EntityRepository
{
}
