<?php

namespace AppBundle\Repository;

/**
 * MobiliteExterneRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobiliteExterneRepository extends \Doctrine\ORM\EntityRepository
{
}
