<?php

namespace AppBundle\Repository;

/**
 * MobiliteDgacRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobiliteDgacRepository extends \Doctrine\ORM\EntityRepository
{
}
