<?php

namespace AppBundle\Repository;

/**
 * MobiliteGeographiqueRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobiliteGeographiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
