<?php

namespace AppBundle\Repository;

/**
 * ObjectifEvalueRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifEvalueRepository extends \Doctrine\ORM\EntityRepository
{
}
