<?php

namespace AppBundle\Repository;

/**
 * ObjectifPasseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifPasseRepository extends \Doctrine\ORM\EntityRepository
{
}
