<?php

namespace AppBundle\Repository;

/**
 * ObjectifAVenirCollectifRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifAVenirCollectifRepository extends \Doctrine\ORM\EntityRepository
{
}
