<?php

namespace AppBundle\Repository;

/**
 * ObjectifEvalueIndividuelRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifEvalueIndividuelRepository extends \Doctrine\ORM\EntityRepository
{
}
