<?php

namespace AppBundle\Repository;

/**
 * ObjectifAVenirRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifFuturParentRepository extends \Doctrine\ORM\EntityRepository
{
}
