<?php

namespace AppBundle\Repository;

/**
 * ObjectifAVenirIndividuelRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifAVenirIndividuelRepository extends \Doctrine\ORM\EntityRepository
{
}
