<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Rlc;
use AppBundle\Entity\Ministere;
use AppBundle\Entity\PerimetreRlc;

/**
 * PerimetreBrhpRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerimetreBrhpRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPerimetresBrhpByRlc(Rlc $rlc)
    {
        $result = [];

        /* @var $perimetreRlc PerimetreRlc */
        foreach ($rlc->getPerimetresRlc() as $perimetreRlc) {
            $result = array_merge($result, $perimetreRlc->getPerimetresBrhp()->toArray());
        }

        return $result;

        /*
        $ministere = $rlc->getMinistere();
        $qb = $this->createQueryBuilder('p');

        $qb->leftJoin('p.perimetreRlc', 'prlc')
            ->leftJoin('prlc.ministere', 'm')
            ->leftJoin('prlc.rlcs', 'rlcs')
            ->where('m = :MINISTERE')
            ->andWhere('rlcs = :RLC')
            ->setParameter('MINISTERE', $ministere)
            ->setParameter('RLC', $rlc);

        return $qb->getQuery()->getResult();
        */
    }

    public function getPerimetresBrhpByMinistere(Ministere $ministere)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->leftJoin('p.perimetreRlc', 'prlc')
            ->leftJoin('prlc.ministere', 'm')
            ->where('m = :MINISTERE')
            ->setParameter('MINISTERE', $ministere);

        return $qb->getQuery()->getResult();
    }
}
