<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Utilisateur;

/**
 * PerimetreRlcRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerimetreRlcRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPerimetresRlcByMinistere(Utilisateur $utilisateur)
    {
        if ($utilisateur->hasRole('ROLE_ADMIN')) {
            $qb = $this->createQueryBuilder('p')
            ->orderBy('p.libelle');
        } else {
            $qb = $this->createQueryBuilder('p')
                ->where('p.ministere = :MINISTERE')
                ->orderBy('p.libelle')
                ->setParameter('MINISTERE', $utilisateur->getMinistere());
        }

        return $qb;
    }
}
