<?php

namespace AppBundle\Repository;

/**
 * PerimetreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerimetreRepository extends \Doctrine\ORM\EntityRepository
{
}
