<?php

namespace AppBundle\Repository;

/**
 * RlcRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RlcRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRlcByEmail($email)
    {
        return $this->findOneByEmail($email);
    }
}
