<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\LockMode;

/**
 * UtilisateurTmpRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurTmpRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupérer un lot d'agents à créer.
     *
     * @param int $nbAgents
     */
    public function getUtilisateursPourCreation($nbAgents)
    {
        $qb = $this->createQueryBuilder('u');

        $query = $qb
                ->where('u.locked IS NULL')
                ->setMaxResults($nbAgents)
                ->getQuery();

        // Positionnement d'un verrou en écriture afin qu'un autre processus ne puisse pas récupérer les mêmes agents
        $query->setLockMode(LockMode::PESSIMISTIC_WRITE);

        return $query->getResult();
    }
}
