imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apcu
        query_cache_driver: apcu
        result_cache_driver: apcu
        second_level_cache:
            enabled: true