# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: '%app.encoders.algorithm%'
            cost: '%app.bcrypt_cost%'

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN_MIN, ROLE_PNC, ROLE_DGAFP, ROLE_RLC, ROLE_BRHP, ROLE_GESTIONNAIRE_RECOURS, ROLE_CONSEILLER_FORMATION, ROLE_SHD, ROLE_AH, ROLE_AGENT]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            #id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email    # Connexion par email / mot de passe
            
    firewalls:
        dev:
            pattern: ^/(_wdt|_profiler|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: "/"
            logout:       true
            anonymous:    true
            logout_on_user_change: true

    access_control:
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*$, role: ROLE_USER }