brhp_index:
    path:     /
    defaults: { _controller: "AppBundle:Brhp:index" }
    methods:  GET

brhp_new:
    path:     /new
    defaults: { _controller: "AppBundle:Brhp:new" }
    methods:  [GET, POST]

brhp_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Brhp:edit" }
    methods:  [GET, POST]
    requirements:
        id: '\d+'
        
brhp_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Brhp:delete" }
    methods:  DELETE
    requirements:
        id: '\d+'