brhp_consult_index:
    path:     /
    defaults: { _controller: "AppBundle:BrhpConsult:index" }
    methods:  GET

brhp_consult_new:
    path:     /new
    defaults: { _controller: "AppBundle:BrhpConsult:new" }
    methods:  [GET, POST]

brhp_consult_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:BrhpConsult:edit" }
    methods:  [GET, POST]
    requirements:
        id: '\d+'
        
brhp_consult_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:BrhpConsult:delete" }
    methods:  DELETE
    requirements:
        id: '\d+'