rlc_index:
    path:     /
    defaults: { _controller: "AppBundle:Rlc:index" }
    methods:  GET

rlc_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Rlc:show" }
    methods:  GET
    requirements:
        id: '\d+'
        
rlc_new:
    path:     /new
    defaults: { _controller: "AppBundle:Rlc:new" }
    methods:  [GET, POST]

rlc_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Rlc:edit" }
    methods:  [GET, POST]
    requirements:
        id: '\d+'
        
rlc_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Rlc:delete" }
    methods:  DELETE
    requirements:
        id: '\d+'