ALTER TABLE CREP_SCL_COMP_TRANS DROP CONSTRAINT FK_EA2CEAA585ECD9A8;
DROP INDEX idx_ea2ceaa585ecd9a8;
DROP INDEX uniq_ea2ceaa584e0fe3e85ecd9a8;
ALTER TABLE CREP_SCL_COMP_TRANS ADD (cree_par_id NUMBER(10) DEFAULT NULL NULL, modifie_par_id NUMBER(10) DEFAULT NULL NULL, libelle CLOB NOT NULL, type_competence VARCHAR2(255) DEFAULT NULL NULL, date_creation TIMESTAMP(0) NOT NULL, date_modification TIMESTAMP(0) NOT NULL);
ALTER TABLE CREP_SCL_COMP_TRANS DROP (COMPETENCE_TRANSVERSE_ID);
ALTER TABLE CREP_SCL_COMP_TRANS ADD CONSTRAINT FK_EA2CEAA5FC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id);
ALTER TABLE CREP_SCL_COMP_TRANS ADD CONSTRAINT FK_EA2CEAA5553B2554 FOREIGN KEY (modifie_par_id) REFERENCES utilisateur (id);
CREATE INDEX IDX_EA2CEAA5FC29C013 ON CREP_SCL_COMP_TRANS (cree_par_id);
CREATE INDEX IDX_EA2CEAA5553B2554 ON CREP_SCL_COMP_TRANS (modifie_par_id);
CREATE UNIQUE INDEX UNIQ_EA2CEAA584E0FE3EBF396750 ON CREP_SCL_COMP_TRANS (crep_scl_id, id);

CREATE SEQUENCE crep_mso3_competence_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE crep_mso3_formation_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE TABLE crep_mso3_competence (id NUMBER(10) NOT NULL, cree_par_id NUMBER(10) DEFAULT NULL NULL, modifie_par_id NUMBER(10) DEFAULT NULL NULL, crep_id NUMBER(10) DEFAULT NULL NULL, libelle VARCHAR2(255) DEFAULT NULL NULL, niveau NUMBER(10) DEFAULT NULL NULL, appreciation CLOB DEFAULT NULL NULL, date_creation TIMESTAMP(0) NOT NULL, date_modification TIMESTAMP(0) NOT NULL, dtype VARCHAR2(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_5C262A02FC29C013 ON crep_mso3_competence (cree_par_id);
CREATE INDEX IDX_5C262A02553B2554 ON crep_mso3_competence (modifie_par_id);
CREATE INDEX IDX_5C262A02C235614F ON crep_mso3_competence (crep_id);
CREATE TABLE crep_mso3_formation (id NUMBER(10) NOT NULL, cree_par_id NUMBER(10) DEFAULT NULL NULL, modifie_par_id NUMBER(10) DEFAULT NULL NULL, crep_id NUMBER(10) DEFAULT NULL NULL, libelle VARCHAR2(255) DEFAULT NULL NULL, commentaires CLOB DEFAULT NULL NULL, formation_suivie NUMBER(1) DEFAULT NULL NULL, demandee_agent NUMBER(1) DEFAULT NULL NULL, avis_shd NUMBER(1) DEFAULT NULL NULL, proposition_ah NUMBER(1) DEFAULT NULL NULL, cpf NUMBER(1) DEFAULT NULL NULL, echeance NUMBER(10) DEFAULT NULL NULL, date_creation TIMESTAMP(0) NOT NULL, date_modification TIMESTAMP(0) NOT NULL, dtype VARCHAR2(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_6553DC8DFC29C013 ON crep_mso3_formation (cree_par_id);
CREATE INDEX IDX_6553DC8D553B2554 ON crep_mso3_formation (modifie_par_id);
CREATE INDEX IDX_6553DC8DC235614F ON crep_mso3_formation (crep_id);
ALTER TABLE crep_mso3_competence ADD CONSTRAINT FK_5C262A02FC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mso3_competence ADD CONSTRAINT FK_5C262A02553B2554 FOREIGN KEY (modifie_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mso3_competence ADD CONSTRAINT FK_5C262A02C235614F FOREIGN KEY (crep_id) REFERENCES crep (id);
ALTER TABLE crep_mso3_formation ADD CONSTRAINT FK_6553DC8DFC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mso3_formation ADD CONSTRAINT FK_6553DC8D553B2554 FOREIGN KEY (modifie_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mso3_formation ADD CONSTRAINT FK_6553DC8DC235614F FOREIGN KEY (crep_id) REFERENCES crep (id);
ALTER TABLE CREP ADD (categorie VARCHAR2(255) DEFAULT NULL NULL, shd_titulaire NUMBER(1) DEFAULT NULL NULL, fonction_exercee_shd VARCHAR2(255) DEFAULT NULL NULL, fonctions_exercees CLOB DEFAULT NULL NULL, cotation_poste VARCHAR2(255) DEFAULT NULL NULL, quotite_travail VARCHAR2(255) DEFAULT NULL NULL, fiche_poste_adaptee NUMBER(1) DEFAULT NULL NULL, appreciation_poste_agent CLOB DEFAULT NULL NULL, contexte_annee_ecoulee CLOB DEFAULT NULL NULL, nature_dossiers_travaux CLOB DEFAULT NULL NULL, resultats_obtenus_par_agent CLOB DEFAULT NULL NULL, contexte_resultats CLOB DEFAULT NULL NULL, appreciation_evaluateur CLOB DEFAULT NULL NULL, elements_particuliers CLOB DEFAULT NULL NULL, obs_agent_sur_son_activite CLOB DEFAULT NULL NULL, objectifs_service CLOB DEFAULT NULL NULL, agents_encadres CLOB DEFAULT NULL NULL, modification_fiche_de_poste CLOB DEFAULT NULL NULL, prise_de_responsabilites CLOB DEFAULT NULL NULL, projet_professionnel CLOB DEFAULT NULL NULL, obs_shd_perspectives_pro CLOB DEFAULT NULL NULL, avis_shd_avancement_grade CLOB DEFAULT NULL NULL, obs_agent_perspectives_pro CLOB DEFAULT NULL NULL, obs_apprec_portees_agent CLOB DEFAULT NULL NULL, obs_conduite_entretien_ah CLOB DEFAULT NULL NULL, obs_apprec_portees_ah CLOB DEFAULT NULL NULL, observations_eventuelles_ah CLOB DEFAULT NULL NULL, fonction_ah VARCHAR2(255) DEFAULT NULL NULL);
ALTER TABLE CREP MODIFY (date_entree_poste DATE DEFAULT NULL);
ALTER TABLE COMPETENCE_POSTE ADD (appreciation CLOB DEFAULT NULL NULL);

ALTER TABLE CREP DROP (SHD_TITULAIRE);

CREATE SEQUENCE crep_mj01formation_envisagee_i START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE crep_mj01_competence_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE crep_mj01formation_suivie_id_s START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE crep_mj01formation_sollicitee_ START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE TABLE crep_mj01formation_envisagee (id NUMBER(10) NOT NULL, crep_id NUMBER(10) NOT NULL, cree_par_id NUMBER(10) DEFAULT NULL NULL, modifie_par_id NUMBER(10) DEFAULT NULL NULL, libelle VARCHAR2(255) NOT NULL, origine NUMBER(10) NOT NULL, date_creation TIMESTAMP(0) NOT NULL, date_modification TIMESTAMP(0) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_F1FA4692C235614F ON crep_mj01formation_envisagee (crep_id);
CREATE INDEX IDX_F1FA4692FC29C013 ON crep_mj01formation_envisagee (cree_par_id);
CREATE INDEX IDX_F1FA4692553B2554 ON crep_mj01formation_envisagee (modifie_par_id);
CREATE TABLE crep_mj01_competence (id NUMBER(10) NOT NULL, cree_par_id NUMBER(10) DEFAULT NULL NULL, modifie_par_id NUMBER(10) DEFAULT NULL NULL, crep_id NUMBER(10) NOT NULL, libelle CLOB NOT NULL, niveau NUMBER(10) DEFAULT NULL NULL, date_creation TIMESTAMP(0) NOT NULL, date_modification TIMESTAMP(0) NOT NULL, dtype VARCHAR2(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_560395F5FC29C013 ON crep_mj01_competence (cree_par_id);
CREATE INDEX IDX_560395F5553B2554 ON crep_mj01_competence (modifie_par_id);
CREATE INDEX IDX_560395F5C235614F ON crep_mj01_competence (crep_id);
CREATE TABLE crep_mj01formation_suivie (id NUMBER(10) NOT NULL, crep_id NUMBER(10) NOT NULL, cree_par_id NUMBER(10) DEFAULT NULL NULL, modifie_par_id NUMBER(10) DEFAULT NULL NULL, libelle VARCHAR2(255) NOT NULL, duree VARCHAR2(255) DEFAULT NULL NULL, date_creation TIMESTAMP(0) NOT NULL, date_modification TIMESTAMP(0) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_316141D0C235614F ON crep_mj01formation_suivie (crep_id);
CREATE INDEX IDX_316141D0FC29C013 ON crep_mj01formation_suivie (cree_par_id);
CREATE INDEX IDX_316141D0553B2554 ON crep_mj01formation_suivie (modifie_par_id);
CREATE TABLE crep_mj01formation_sollicitee (id NUMBER(10) NOT NULL, crep_id NUMBER(10) NOT NULL, cree_par_id NUMBER(10) DEFAULT NULL NULL, modifie_par_id NUMBER(10) DEFAULT NULL NULL, libelle VARCHAR2(255) NOT NULL, origine NUMBER(10) NOT NULL, date_creation TIMESTAMP(0) NOT NULL, date_modification TIMESTAMP(0) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_56145935C235614F ON crep_mj01formation_sollicitee (crep_id);
CREATE INDEX IDX_56145935FC29C013 ON crep_mj01formation_sollicitee (cree_par_id);
CREATE INDEX IDX_56145935553B2554 ON crep_mj01formation_sollicitee (modifie_par_id);
ALTER TABLE crep_mj01formation_envisagee ADD CONSTRAINT FK_F1FA4692C235614F FOREIGN KEY (crep_id) REFERENCES crep (id);
ALTER TABLE crep_mj01formation_envisagee ADD CONSTRAINT FK_F1FA4692FC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mj01formation_envisagee ADD CONSTRAINT FK_F1FA4692553B2554 FOREIGN KEY (modifie_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mj01_competence ADD CONSTRAINT FK_560395F5FC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mj01_competence ADD CONSTRAINT FK_560395F5553B2554 FOREIGN KEY (modifie_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mj01_competence ADD CONSTRAINT FK_560395F5C235614F FOREIGN KEY (crep_id) REFERENCES crep (id);
ALTER TABLE crep_mj01formation_suivie ADD CONSTRAINT FK_316141D0C235614F FOREIGN KEY (crep_id) REFERENCES crep (id);
ALTER TABLE crep_mj01formation_suivie ADD CONSTRAINT FK_316141D0FC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mj01formation_suivie ADD CONSTRAINT FK_316141D0553B2554 FOREIGN KEY (modifie_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mj01formation_sollicitee ADD CONSTRAINT FK_56145935C235614F FOREIGN KEY (crep_id) REFERENCES crep (id);
ALTER TABLE crep_mj01formation_sollicitee ADD CONSTRAINT FK_56145935FC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id);
ALTER TABLE crep_mj01formation_sollicitee ADD CONSTRAINT FK_56145935553B2554 FOREIGN KEY (modifie_par_id) REFERENCES utilisateur (id);
ALTER TABLE CREP ADD (service_shd VARCHAR2(255) DEFAULT NULL NULL, obs_agent_objectifs_evalues CLOB DEFAULT NULL NULL, marge_evol_comp_pro NUMBER(10) DEFAULT NULL NULL, marge_evol_aptitudes_pro NUMBER(10) DEFAULT NULL NULL, marge_evol_qualites_pro NUMBER(10) DEFAULT NULL NULL, marge_evol_capacite_encad NUMBER(10) DEFAULT NULL NULL, marge_evolution_globale NUMBER(10) DEFAULT NULL NULL, niveau_performance_globale NUMBER(10) DEFAULT NULL NULL, obs_competences_pro CLOB DEFAULT NULL NULL, obs_aptitudes_pro CLOB DEFAULT NULL NULL, obs_qualites_relationnelles CLOB DEFAULT NULL NULL, obs_capacites_encadrement CLOB DEFAULT NULL NULL, observations_globale CLOB DEFAULT NULL NULL, note_agent NUMBER(10) DEFAULT NULL NULL, observations_shd CLOB DEFAULT NULL NULL, perspectives_evol_service CLOB DEFAULT NULL NULL, perspectives_evol_fonction CLOB DEFAULT NULL NULL, observations_shd_formation CLOB DEFAULT NULL NULL, connaissances_institution CLOB DEFAULT NULL NULL, connaissances_professionnelles CLOB DEFAULT NULL NULL, experience_encadrement CLOB DEFAULT NULL NULL, capacites_decisions CLOB DEFAULT NULL NULL, obs_agent_deroul_entretien CLOB DEFAULT NULL NULL, obs_agent_apprec_portees CLOB DEFAULT NULL NULL, motif_absence_entretien CLOB DEFAULT NULL NULL);
ALTER TABLE CREP MODIFY (nom_usage_shd VARCHAR2(255) DEFAULT NULL, prenom_shd VARCHAR2(255) DEFAULT NULL);

commit;
exit;