<?php

namespace AppBundle\Repository\CrepRepository\CrepMj01Repository;

/**
 * CrepDgacRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepDgacRepository extends \Doctrine\ORM\EntityRepository
{
}
