CREATE SEQUENCE crep_scl_comp_trans_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE TABLE crep_scl_comp_trans (id NUMBER(10) NOT NULL, crep_scl_id NUMBER(10) NOT NULL, competence_transverse_id NUMBER(10) NOT NULL, niveauAcquis NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id));
CREATE INDEX IDX_EA2CEAA584E0FE3E ON crep_scl_comp_trans (crep_scl_id);
CREATE INDEX IDX_EA2CEAA585ECD9A8 ON crep_scl_comp_trans (competence_transverse_id);
CREATE UNIQUE INDEX UNIQ_EA2CEAA584E0FE3E85ECD9A8 ON crep_scl_comp_trans (crep_scl_id, competence_transverse_id);
ALTER TABLE crep_scl_comp_trans ADD CONSTRAINT FK_EA2CEAA584E0FE3E FOREIGN KEY (crep_scl_id) REFERENCES crep (id);
ALTER TABLE crep_scl_comp_trans ADD CONSTRAINT FK_EA2CEAA585ECD9A8 FOREIGN KEY (competence_transverse_id) REFERENCES competence_transverse (id);
ALTER TABLE CREP ADD (rang VARCHAR2(255) DEFAULT NULL NULL, echelon_terminal VARCHAR2(255) DEFAULT NULL NULL, mention_alerte CLOB DEFAULT NULL NULL);
ALTER TABLE FORMATION_DEMANDEE_AGENT MODIFY (dif NUMBER(1) DEFAULT NULL NULL, priorite NUMBER(10) DEFAULT NULL NULL);
ALTER TABLE FORMATION_DEMANDEE_EMPLOYEUR MODIFY (priorite NUMBER(10) DEFAULT NULL NULL);
ALTER TABLE FORMATION_REGLEMENTAIRE MODIFY (priorite NUMBER(10) DEFAULT NULL NULL);
ALTER TABLE FORMATION_DEMANDEE_ADMIN MODIFY (priorite NUMBER(10) DEFAULT NULL NULL);

CREATE SEQUENCE crep_ac_technique_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE TABLE crep_ac_technique (id NUMBER(10) NOT NULL, crep_ac_id NUMBER(10) DEFAULT NULL NULL, niveauAcquis NUMBER(10) DEFAULT NULL NULL, libelle CLOB DEFAULT NULL NULL, observations CLOB DEFAULT NULL NULL, PRIMARY KEY(id));
CREATE INDEX IDX_79640509A75E2B2 ON crep_ac_technique (crep_ac_id);
ALTER TABLE crep_ac_technique ADD CONSTRAINT FK_79640509A75E2B2 FOREIGN KEY (crep_ac_id) REFERENCES crep (id);

commit;
exit;