<?php

namespace AppBundle\Repository\CrepRepository\CrepMindef01Repository;

/**
 * CrepMindef01CompetenceTransverseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMindef01CompetenceTransverseRepository extends \Doctrine\ORM\EntityRepository
{
}
