REM INSERTING into FORMATION_A_VENIR_2016
SET DEFINE OFF;
SET SQLBLANKLINES ON;
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (1,'marie-josee.collin@intradef.gouv.fr','EXCEL 2010 - TABLEAUX DE BORD');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (2,'marie-eliane.darles@intradef.gouv.fr','La gestion des conflits');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (3,'chantal.duluc@intradef.gouv.fr','EXCEL 2010 - Fonctions avancées');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (4,'armelle1.friconnet@intradef.gouv.fr','DROIT SYNDICAL ET DIALOGUE SOCIAL');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (5,'agnes.moussinat@intradef.gouv.fr','SACE écrit support papier (fascicule)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (6,'sylvie.serre@intradef.gouv.fr','ANALYSE DE TEXTE : ANALYSE, COMPREHENSION ET REFORMULATION');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (7,'sylvie.serre@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (8,'sylvie.serre@intradef.gouv.fr','POWERPOINT 2010 - Niveau 1 initiation');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (9,'sylvie.serre@intradef.gouv.fr','WORD 2010 - Formulaires et Modèles');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (10,'lucette.delcombel@intradef.gouv.fr','Prise de parole en public');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (11,'pierrette.adeux-planchard@intradef.gouv.fr','INTRODUCTION A LA GRH');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (12,'pierrette.adeux-planchard@intradef.gouv.fr','Mettre en valeur ses compétences et potentiel');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (14,'didier1.schmitt@intradef.gouv.fr','EFFECTIFS en mars 2017');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (15,'roseline.gassner@intradef.gouv.fr','CURSUS GESTIONNAIRE RH MODULE OUVRIER ETAT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (16,'francoise.chaynes@intradef.gouv.fr','Qualité et processus maintenance - du diagnostic à l''audit');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (19,'stephanie.bonnefond@intradef.gouv.fr','gestion administrative et paie des ouvriers de l''Etat');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (20,'marie-eve.mariou@intradef.gouv.fr','POWERPOINT 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (21,'marie-eve.mariou@intradef.gouv.fr','ECRIRE COMME UN JOURNALISTE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (22,'marie-eve.mariou@intradef.gouv.fr','Savoir synthétiser un dossier');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (23,'martine.junique@intradef.gouv.fr','ECRIRE COMME UN JOURNALISTE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (24,'mireille.millard@intradef.gouv.fr','Améliorer son leadership - S000002559 - Maîtrise');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (27,'jocelyn.lagoutte@intradef.gouv.fr','GPRH S000007016');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (28,'nathalie.dalby@intradef.gouv.fr','ETRE RESPONSABLE RH (validee en 2016 reportée en 2017) code S000008366');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (29,'anne-lise.juguet@intradef.gouv.fr','CONDUITE DE PROJET');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (30,'anne-lise.juguet@intradef.gouv.fr','Préparation au tour extérieur d''administrateur civil');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (31,'denis.theobald@intradef.gouv.fr','Excel 2010 - Fonctions avancées');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (32,'denis.theobald@intradef.gouv.fr','WORD 2010 - perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (33,'marie-annick.sauvee-lorant@intradef.gouv.fr','Sans objet l''intéressée ayant été rayée des cadres au 1er janvier 2017');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (34,'sylvie.diolez@intradef.gouv.fr','DROIT SYNDICAL ET DIALOGUE SOCIAL                           																									S000005673');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (35,'chantal.pellois@intradef.gouv.fr','Sans objet l''intéressée devant être rayée des cadres le 1er avril 2017');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (36,'stephanie.labeyrie@intradef.gouv.fr','Animer une équipe');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (37,'germaine.minker@intradef.gouv.fr','MANAGEMENT ET COHESION EQUIPE S000002555');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (38,'jean.chevreteau@intradef.gouv.fr','Formation des formateurs');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (39,'theary.masse@intradef.gouv.fr','Préparer son CV, sa lettre de motivation et son entretien');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (40,'theary.masse@intradef.gouv.fr','Gestion du stress');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (41,'christine.valerio@intradef.gouv.fr','Formation IRA (en ligne) - Hors plan');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (42,'rabia.bouomrane@intradef.gouv.fr','Culture défense');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (43,'rabia.bouomrane@intradef.gouv.fr','Europe');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (44,'karine.langibout@intradef.gouv.fr','WORD 2010 - Niveau 1 Initiation');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (45,'karine.langibout@intradef.gouv.fr','EXCEL 2010 - Tableaux de bord');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (46,'philippe.ninlias@intradef.gouv.fr','POWERPOINT 2010 - Niveau 1 initiation');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (47,'veronique.donnart@intradef.gouv.fr','Mener un entretien professionnel en E-learning');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (48,'arlette.bissieres@intradef.gouv.fr','Sensibilisation aux Risques Psychosociaux');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (49,'annie.copinet@intradef.gouv.fr','CONDUITE DU CHANGEMENT (S000007007)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (50,'annie.copinet@intradef.gouv.fr','DEMARCHE DU CONTRÔLE DE GESTION (S000007660)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (51,'thierry.bollenot@intradef.gouv.fr','Les grands principes du PAR (S000010322)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (52,'thierry.bollenot@intradef.gouv.fr','Nouvelles organisations territoriales des l''administration (S000008352)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (53,'maryse.nicod@intradef.gouv.fr','Anglais intensif niveau intermediate-S000003316 (formation non retenue par l''administration)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (54,'maryse.nicod@intradef.gouv.fr','EXCEL 2010  Intermédiaire - S000011281');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (55,'maryse.nicod@intradef.gouv.fr','Naviguer et communiquer avec Internet - S000007222');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (56,'david.retiere@intradef.gouv.fr','La prise de notes et le compte-rendu de réunion (S000007123) (TCC04)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (57,'david.retiere@intradef.gouv.fr','Management et cohésion d’équipe (S000002555) (TMC02)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (58,'karima.krim@intradef.gouv.fr','Améliorer ses écrits professionnels');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (59,'karima.krim@intradef.gouv.fr','Rédaction administrative (courriers administratifs)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (60,'karima.krim@intradef.gouv.fr','Rédaction du dossier RAEP');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (61,'nicolas.schmitt@intradef.gouv.fr','"Business Objects XI Utilisateur Web Intelligence"		S000009859');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (62,'nicolas.schmitt@intradef.gouv.fr','"Améliorer ses relations par l''assertivité"  S000002570');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (63,'frederic.delhaye@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (64,'pascale.deschamps-de-paillette@intradef.gouv.fr','Les enjeux de l''orthographe');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (65,'pascale.deschamps-de-paillette@intradef.gouv.fr','risques psychosociaux');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (66,'pascale.deschamps-de-paillette@intradef.gouv.fr','PSC1');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (67,'christiane.lecocq@intradef.gouv.fr','Stage de préparation à la retraite');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (68,'claudine.berne@intradef.gouv.fr','Améliorer ses relations par l''assertivité');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (69,'claudine.berne@intradef.gouv.fr','BILAN DE COMPETENCES');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (70,'claudine.berne@intradef.gouv.fr','CHOISIR LES CRITERES -SELECTIONNER LES OFFRES (PERFECT)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (71,'frederique.lusseau@intradef.gouv.fr','Néant');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (72,'philippe.jedynak@intradef.gouv.fr','PERFECTIONNEMENT PRATIQUE DE L''AUDIT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (73,'philippe.jedynak@intradef.gouv.fr','CURSUS CONTROLEUR DE GESTION');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (74,'philippe.jedynak@intradef.gouv.fr','PILOTAGE DES PROCESSUS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (75,'corinne2.garcia@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (76,'corinne2.garcia@intradef.gouv.fr','Visual basic pour Excel (VBA)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (77,'corinne2.garcia@intradef.gouv.fr','EXCEL 2010 - Tableaux de bord');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (78,'anne.tournus@intradef.gouv.fr','NEANT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (79,'marie-christine.chapon@intradef.gouv.fr','S000011752	Mener un entretien professionnel');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (80,'marie-christine.chapon@intradef.gouv.fr','S000010095 Renseigner son dossier RAEP');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (81,'marie-therese.bernardin@intradef.gouv.fr','Se préparer à la retraite (formation validée au titre  de 2017');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (82,'sebastien.cerveau@intradef.gouv.fr','Initiation à la gestion des ressources humaines');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (83,'sebastien.cerveau@intradef.gouv.fr','Piloter la gestion prévisionnelle des ressources humaines (GPRH)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (84,'charles.gaulupeau@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (85,'charles.gaulupeau@intradef.gouv.fr','EXCEL 2010 - Tableaux de bord');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (86,'frederique.meslier@intradef.gouv.fr','ALLIANCE - GESTION ADMINISTRATIVE DES AGENTS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (87,'frederique.meslier@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (88,'rose-marie.le-villo@intradef.gouv.fr','Légistique niveau perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (89,'rose-marie.le-villo@intradef.gouv.fr','Initiation à la GPEC interne');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (90,'philippe.sauvanet@intradef.gouv.fr','CARTOGRAPHIE ET MANAGEMENT RISQUES');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (91,'ingrid.gaudin@intradef.gouv.fr','ADVP organisé par le SGAR');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (92,'ingrid.gaudin@intradef.gouv.fr','SESSION TECHNIQUE RECHERCHE D''EMPLOI (STRE) 3 jours (prestation gratuire de l''ARD Rennes)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (93,'ingrid.gaudin@intradef.gouv.fr','SESSION BILAN D''ORIENTATION (SBO) 5 jours (prestation gratuite de l''ARD Rennes)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (94,'laurent.suteau@intradef.gouv.fr','Développement personnel (MBTI)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (95,'jean-francois.cavallo@intradef.gouv.fr','NEANT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (96,'benoit.tourment@intradef.gouv.fr','Initiation au process com (S0000010125)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (97,'helene.petit@intradef.gouv.fr','Formation personnalisée POWERPOINT 2010 e-Learning');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (98,'muriel.duriez@intradef.gouv.fr','Naviguer et communiquer avec Internet / S000007222');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (100,'marie-pierre.marsella@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (101,'laetitia.loron@intradef.gouv.fr','ANALYSE DES EMPLOIS ET DES EFFECTIFS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (102,'laetitia.loron@intradef.gouv.fr','La GPEEC');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (103,'laetitia.loron@intradef.gouv.fr','Utilisation de l''application OMSAR 2');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (104,'eric.le-droumaguet@intradef.gouv.fr','Formation de formateurs (mise à jour des compétences déjà détenues en qualité de formateur  ALLIANCE)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (105,'eric.le-droumaguet@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (106,'marie-berthe.badie@intradef.gouv.fr','Management des cadres intermédiaires');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (107,'stephanie.bonnefond@intradef.gouv.fr','détermination des différents droits à pension des ouvriers de l''Etat (au titre des carrières longues, Travaux insalubres, invalidité, Amiante...)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (108,'stephanie.bonnefond@intradef.gouv.fr','cursus gestionnaire RH - module ouvriers de l''Etat');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (109,'marylene.pechmagre-caminade@intradef.gouv.fr','Les grands principes du PAR en E-learning');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (110,'eric.sartory@intradef.gouv.fr','médiation professionnelle (si la formation n''est pas réalisée en 2017)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (111,'caroline.sobol@intradef.gouv.fr','COMMUNIQUER SUR LA FORMATION CONTINUE                       																									S000006789');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (112,'caroline.sobol@intradef.gouv.fr','CONSTRUIRE UN PLAN DE FORMATION                             																									S000008366');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (113,'caroline.sobol@intradef.gouv.fr','L''INNOVATION EN FORMATION                                   																									S000008366');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (114,'gregoire.despres@intradef.gouv.fr','Savoir synthétiser un dossier');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (115,'gregoire.despres@intradef.gouv.fr','Améliorer ses écrits professionnels');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (116,'odile.gaillard@intradef.gouv.fr','EXCEL 2010 - Tableaux de bord');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (117,'odile.gaillard@intradef.gouv.fr','Savoir gérer ses émotions');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (118,'odile.gaillard@intradef.gouv.fr','POWERPOINT 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (119,'nathalie.ponroy@intradef.gouv.fr','CYCLE SUPERIEUR DE MANAGEMENT GENERAL');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (120,'marilyse.dupont@intradef.gouv.fr','COLLECTIF DE TRAVAIL AU HANDICAP PSYCHIQUE                  																									S000008377');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (121,'odile.billet@intradef.gouv.fr','Initiation à la qualité');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (122,'odile.billet@intradef.gouv.fr','Savoir gérer ses émotions');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (123,'fabienne.cosnefroy@intradef.gouv.fr','GESTION PREVISIONNELLE DES RESSOURCES HUMAINES');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (124,'christiane.massicot@intradef.gouv.fr','Rédaction administrative (courriers administratifs)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (125,'christiane.massicot@intradef.gouv.fr','Sensibilisation achat et finances publics pour des agents de Niv 1 et 2');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (126,'maite.azimont@intradef.gouv.fr','Maintenir dans l''emploi un agent en situation de handicap');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (127,'maite.azimont@intradef.gouv.fr','Gestion des situations délicates et conflictuelles au sein d''un service');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (128,'maite.azimont@intradef.gouv.fr','Savoir renseigner son dossier RAEP');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (129,'isabelle.pleynet@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (130,'isabelle.pleynet@intradef.gouv.fr','Mener un entretien professionnel en E-learning');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (131,'isabelle.pleynet@intradef.gouv.fr','POWERPOINT 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (132,'annick.meyer@intradef.gouv.fr','Contrôle interne - Stage CFMD référence S000011987');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (133,'patrick.laurens@intradef.gouv.fr','Cursus cadres confirmés si non réalisé en 2017');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (134,'regine.gaborit@intradef.gouv.fr','Formation sur les prescriptions');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (135,'daniel.bonin@intradef.gouv.fr','Améliorer ses relations par l''assertivité');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (136,'daniel.bonin@intradef.gouv.fr','FONDAMENTAUX CONTENTIEUX ADMIINISTRATIF');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (137,'patricia.guillaume@intradef.gouv.fr','Formation au dialogue social');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (138,'patricia.guillaume@intradef.gouv.fr','Formation au langage des signes niveau 2');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (139,'patricia.guillaume@intradef.gouv.fr','Etre capable de constituer un dossier RAEP en vue d''un examen professionnel');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (140,'catherine.astier@intradef.gouv.fr','VBA Excel S000009896');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (141,'joseph.tibource@intradef.gouv.fr','Les impacts de la LOLF sur les ressources humaines');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (142,'isabelle.tipaka@intradef.gouv.fr','Formation relative à l''ergonomie au travail');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (143,'brigitte.emerit@intradef.gouv.fr','DETERMINATION DES DROITS A PENSION AU TITRE DU HANDICAP, DE L''INVALIDITE, DU PARENT DE 3 ENFANTS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (144,'brigitte.emerit@intradef.gouv.fr','COORDINATION PENSION INTER-REGIMES (DETERMINATION DES TRIMESTRES COTISES)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (145,'laurent.suteau@intradef.gouv.fr','Développement managérial');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (146,'laurent.suteau@intradef.gouv.fr','Aide à la décision et au pilotage');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (147,'francoise.helmer@intradef.gouv.fr','NEANT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (148,'veronique.lebrun@intradef.gouv.fr','Améliorer ses écrits professionnels');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (149,'veronique.lebrun@intradef.gouv.fr','ANALYSE DE TEXTE : ANALYSE, COMPREHENSION ET REFORMULATION');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (150,'dominique.mary@intradef.gouv.fr','Initation au process com');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (151,'chantal.lavedrine@intradef.gouv.fr','S 000007575 -  CAP AVANCEMENT - Niveau M');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (152,'chantal.lavedrine@intradef.gouv.fr','S 000007850   -  GESTION DES AGENTS CONTRACTUELS - Niveau M');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (153,'germaine.minker@intradef.gouv.fr','Participation aux conférences organisées par l''IRA sur les sujets d''actualité de la fonction publique');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (154,'francine.naudais@intradef.gouv.fr','PARCOURS JEUNES MANAGERS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (155,'francine.naudais@intradef.gouv.fr','Fondamentaux liés au reglement des contentieux');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (156,'celine.gineys@intradef.gouv.fr','Sensibilisation au contrôle interne');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (157,'nathalie.botella@intradef.gouv.fr','Formation GA et PAIE (perfectionnement)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (158,'nathalie.botella@intradef.gouv.fr','WORD 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (159,'gwendoline1.haentjens@intradef.gouv.fr','Formation statutaire des attachés');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (160,'gwendoline1.haentjens@intradef.gouv.fr','Retraites initiation');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (161,'gwendoline1.haentjens@intradef.gouv.fr','Les outils et méthodes de la GPEEC dans la fonction publique');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (162,'valerie.andrieux@intradef.gouv.fr','Allince requête Business Object   S000006920');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (163,'sophie.gourio@intradef.gouv.fr','SENSIBILISATION AUX ACHATS PUBLICS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (164,'maud.francois@intradef.gouv.fr','CONTRÔLE INTERNE (CFMD)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (165,'jean-charles.bucquet@intradef.gouv.fr','RPS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (166,'marie-odile.sorcelle@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (167,'patrick.nogue@intradef.gouv.fr','SANS OBJET : DEPART RETRAITE LE 01/05/2017');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (168,'maud.francois@intradef.gouv.fr','LES MÉTHODES ET OUTILS DE LA MAÎTRISE DES RISQUES (AMDEC) (CFMD)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (169,'michael.belot@intradef.gouv.fr','Norme ISO 9001 v2015 : Comprendre les exigences (AFNOR)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (170,'michael.belot@intradef.gouv.fr','ISO 31000 : Maîtriser les fondamentaux du management de risque');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (171,'olivier.lablanche@intradef.gouv.fr','ALLIANCE - RESPONSABLE EN LECTURE SEULE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (172,'olivier.lablanche@intradef.gouv.fr','Formation de formateurs');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (173,'guylaine.raud@intradef.gouv.fr','CAP - AVANCEMENT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (174,'yves.gruson@intradef.gouv.fr','Note Administrative - Préparation aux Concours & Examens - S000007940');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (175,'jean-louis.khaznadar@intradef.gouv.fr','NEANT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (176,'monique.magadoux@intradef.gouv.fr','SANS OBJET : DEPART A LA RETRAITE 2017');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (177,'elisabeth1.guillou@intradef.gouv.fr','Communication Management Cat A');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (178,'isabelle.berteau@intradef.gouv.fr','SACS écrit support papier (fascicule)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (179,'frederic.boyon@intradef.gouv.fr','atelier compétences');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (180,'emily.jourde@intradef.gouv.fr','POWERPOINT 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (181,'martine.bechir@intradef.gouv.fr','PREPARER LE PASSAGE A MA RETRAITE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (184,'isabelle.berteau@intradef.gouv.fr','Formation de formateurs');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (185,'valerie.lasbarreres-candau@intradef.gouv.fr','De la faute au conseil de discipline - S000008370');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (186,'benoit.pastor@intradef.gouv.fr','Management d''une équipe');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (187,'benoit.pastor@intradef.gouv.fr','Formations spécialisées au nouveau domaine d''emploi');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (188,'celine1.riviere@intradef.gouv.fr','FORMATION DROIT DES CONCOURS  S000008393');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (189,'marie-helene.damblade@intradef.gouv.fr','Les clés de la communication managériale (S000008950) P1');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (190,'marie-helene.damblade@intradef.gouv.fr','Formation à la déontologie (S0000011679) P2');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (191,'valerie.lachal@intradef.gouv.fr','NEANT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (192,'ousmane.aoudou@intradef.gouv.fr','Communication Management Cat B');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (193,'olivier.lablanche@intradef.gouv.fr','La GAPaye : Formation à outil ALLIANCE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (194,'olivier.lablanche@intradef.gouv.fr','Métier de la paie personnels civils ouvriers');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (195,'chantal.peybernes@intradef.gouv.fr','Savoir gérer ses émotions');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (196,'chantal.peybernes@intradef.gouv.fr','Stage de prèparation à la retraite');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (197,'stephane.lheureux@intradef.gouv.fr','Préparation à la sélection au tour extérieur des administrateurs civils');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (198,'stephane.lheureux@intradef.gouv.fr','Piloter et accompagner les projets de transformation (Ecole de la modernisation de l''État)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (199,'stephane.lheureux@intradef.gouv.fr','Cursus responsable des ressources humaines (IGPDE)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (200,'isabelle.blache-mourey@intradef.gouv.fr','formation processus qualité et controle interne');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (201,'mireille.lassalle@intradef.gouv.fr','Power Point niveau 1');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (202,'jean.barthomeuf@intradef.gouv.fr','PARCOURS CADRES CONFIRMES');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (203,'amira.belbachir@intradef.gouv.fr','contentieux administratif perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (204,'patricia.tortes@intradef.gouv.fr','Initiation au processus de la communication - S000010125 - 3 jours');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (205,'patricia.tortes@intradef.gouv.fr','Sensibilisation à l’achat public et finances publiques pour agents de Niv I et II - S000011498 - 2 jours');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (206,'patricia.tortes@intradef.gouv.fr','Naviguer et communiquer avec Internet - S000007222 - 1 jour');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (207,'elie.le-cam@intradef.gouv.fr','DIALOGUER EFFICACEMENT AVEC LES REPRESENTANTS DU PERSONNEL');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (208,'christophe.delannoy@intradef.gouv.fr','Réglementation et gestion des ouvriers de l''Etat');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (209,'christophe.delannoy@intradef.gouv.fr','Introduction Finances Publiques');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (210,'veronique.dupuis@intradef.gouv.fr','Ressources humaines - Module pensions');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (211,'jocelyne1.laurent@intradef.gouv.fr','Anglais intensif niveau intermediate');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (212,'corinne.dousson@intradef.gouv.fr','entretenir sa mémoire');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (213,'julie.perilleau@intradef.gouv.fr','EXCEL 2010 - Niveau 1 Initiation');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (216,'cecile.alaimo@intradef.gouv.fr','Renseigner son dossier RAEP');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (217,'cecile.alaimo@intradef.gouv.fr','SACE écrit support informatique (CDRom)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (218,'morgane.debever@intradef.gouv.fr','PARCOURS JEUNES MANAGERS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (219,'anne-marie.poncet@intradef.gouv.fr','cycle supérieur de management CFMD');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (220,'daniele.tolu@intradef.gouv.fr','ISO 27005 - Certified Risk Manager');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (223,'annie.nicol@intradef.gouv.fr','ALLIANCE - RESPONSABLE EN LECTURE SEULE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (224,'annie.nicol@intradef.gouv.fr','Communication Management Cat A');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (225,'annie.nicol@intradef.gouv.fr','NEGOCIATION AVEC DES PARTENAIRES SOCIAUX');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (227,'nathalie.girbal@intradef.gouv.fr','formation CERH PC - niveau maitrise');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (229,'nathalie.girbal@intradef.gouv.fr','Formation CERH PC - niveau expertise');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (233,'maryvette.meslin@intradef.gouv.fr','CALCUL DROITS REMUNERATION AGENTS BERKANI ET DROIT PUBLIC');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (234,'julien.chesnel@intradef.gouv.fr','Améliorer ses relations par l''assertivité');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (235,'julien.chesnel@intradef.gouv.fr','CALCUL DROITS REMUNERATION AGENTS BERKANI ET DROIT PUBLIC');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (236,'sophie1.georges@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (237,'magali.bellot@intradef.gouv.fr','Voir ci-dessous');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (238,'nathalie.veillon@intradef.gouv.fr','Gestion administrative paye des fonctionnaires de l''Etat');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (239,'stevens.fried@intradef.gouv.fr','1. PARCOURS JEUNES MANAGERS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (240,'christophe1.martins@intradef.gouv.fr','CALCUL DROITS REMUNERATION AGENTS BERKANI ET DROIT PUBLIC');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (241,'michael.belot@intradef.gouv.fr','Piloter et accompagner un projet de transformation (Ecole de la modernisation de l''État)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (242,'caroline.perot@intradef.gouv.fr','FONDAMENTAUX CONTENTIEUX ADMIINISTRATIF');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (243,'elie.le-cam@intradef.gouv.fr','ETRE MANAGER POUR LA 1ERE FOIS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (244,'elie.le-cam@intradef.gouv.fr','Management et cohésion d''équipe');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (245,'anne.godest@intradef.gouv.fr','AMELIORER SES RELATIONS PAR L ASSERTIVITE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (246,'eliane.besnard@intradef.gouv.fr','SANS OBJET - DEPART RETRAITE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (247,'stevens.fried@intradef.gouv.fr','2. Développement managérial (Ecole de la modernisation de l''État)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (248,'arnaud.de-camproger@intradef.gouv.fr','Renseigner son dossier RAEP');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (249,'christelle.richer@intradef.gouv.fr','Initiation à la qualité');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (250,'christelle.richer@intradef.gouv.fr','Mettre en valeur ses compétences et potentiel');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (251,'christelle.richer@intradef.gouv.fr','La gestion des conflits');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (252,'arnaud.louvigne@intradef.gouv.fr','GPRH (2ème session du CFMD en novembre)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (253,'arnaud.louvigne@intradef.gouv.fr','gestion du temps, stress et délégation (CFMD 3ème ou 4ème session)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (254,'sylvie.mahe-guerin@intradef.gouv.fr','Savoir synthétiser un dossier');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (255,'agnes.chaine-rommel@intradef.gouv.fr','Mettre en valeur ses compétences et potentiel');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (256,'agnes.chaine-rommel@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (257,'gerard.chenot@intradef.gouv.fr','Initiation à la qualité');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (258,'marylene.piot@intradef.gouv.fr','formation RAEP');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (259,'nadine.pitois@intradef.gouv.fr','FORMATION sur la construction d''un tableau de bord');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (260,'nadine.pitois@intradef.gouv.fr','formation power point expert');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (261,'laurent.valy@intradef.gouv.fr','La responsabilité civile, pénale, et administrative des fonctionnaires (code formation : S000011698)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (262,'christelle.bonnet@intradef.gouv.fr','CHORUS Programmation');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (263,'christelle.bonnet@intradef.gouv.fr','Note administrative - Préparation concours et examens');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (264,'reine.sanchez@intradef.gouv.fr','CURSUS CONSEILLER MOBILITE CARRIERE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (265,'isabelle.filbien@intradef.gouv.fr','PILOTAGE DE LA MASSE SALARIALE S0000012393');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (266,'isabelle.filbien@intradef.gouv.fr','CURSUS CONTROLEUR DE GESTION S000007654');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (267,'alain.fong-yam-soy@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (269,'delphine.metivier@intradef.gouv.fr','Formation sur les RPS au CFMD');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (270,'francoise.sachot@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (271,'francoise.sachot@intradef.gouv.fr','CURSUS GESTIONNAIRE RH - MODULE CONTRACTUELS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (272,'caroline.marandat@intradef.gouv.fr','Renseigner son dossier RAEP');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (273,'virginie.boursier@intradef.gouv.fr','Gestion administrative des fonctionnaires de l''Etat');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (274,'virginie.boursier@intradef.gouv.fr','Statut des fonctionnaires de l''Etat');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (275,'virginie.boursier@intradef.gouv.fr','Reglementation et gestion des Ouvriers de l''Etat');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (276,'marion.dymel@intradef.gouv.fr','PARCOURS JEUNES MANAGERS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (277,'marion.dymel@intradef.gouv.fr','Pilotage de la masse salariale et des emplois');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (278,'marion.dymel@intradef.gouv.fr','ENJEUX ET PERSPECTIVES DES FINANCES PUBLIQUES DE L ETAT');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (279,'nadine.pitois@intradef.gouv.fr','formation au management');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (280,'francois.demets@intradef.gouv.fr','Conduite du changement');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (281,'dominique.couloigner@intradef.gouv.fr','Optimiser sa veille juridique');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (282,'albane.sauton@intradef.gouv.fr','ETRE MANAGER POUR LA 1ERE FOIS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (283,'albane.sauton@intradef.gouv.fr','Améliorer sa gestion du temps');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (284,'albane.sauton@intradef.gouv.fr','ANALYSE DES EMPLOIS ET DES EFFECTIFS');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (285,'serge.erramoun@intradef.gouv.fr','Les impacts de la LOLF sur les ressources humaines');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (286,'serge.erramoun@intradef.gouv.fr','Excel perfectionnement (formation programmé  en 2017)');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (287,'frederique.perret@intradef.gouv.fr','Piloter la gestion prévisionnelle des ressources humaines - Code Stage Alliance : S000007983');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (288,'frederique.perret@intradef.gouv.fr','Les impacts de la LOLF sur les ressources humaines - Code Stage Alliance : S000007860');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (289,'frederique.perret@intradef.gouv.fr','Formation Excel 2010 - Niveau 3 perfectionnement- Code stage Alliance : S000009661');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (290,'eliane.besnard@intradef.gouv.fr','SANS OBJET - DEPART RETRAITE');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (291,'cecile.capcarrere@intradef.gouv.fr','Initiation à la qualité');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (292,'pascal.baetche@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire/  S000011281');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (293,'pascal.baetche@intradef.gouv.fr','Piloter la gestion prévsionnelle des ressources humaines/  S00007983');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (294,'pascal.baetche@intradef.gouv.fr','Constituer un dossier RAEP, présenter son parcours à l''oral/  S000007608');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (295,'chantal.gignac@intradef.gouv.fr','Stage de préparation à la retraite');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (296,'martine.subirana@intradef.gouv.fr','Comprendre un texte juridique');
Insert into FORMATION_A_VENIR_2016 ("ID","EMAIL","LIBELLE") values (297,'martine.subirana@intradef.gouv.fr','Maîtrise de soi');
commit;
exit;
