REM INSERTING into FORMATION_DEMANDEE_ADMIN_2016
SET DEFINE OFF;
SET SQLBLANKLINES ON;
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (1,'catherine.gueroult@intradef.gouv.fr','ALLIANCE - GESTION ADMINISTRATIVE DES AGENTS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (2,'catherine.gueroult@intradef.gouv.fr','CULTURE DEFENSE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (3,'lucette.delcombel@intradef.gouv.fr','CONDUITE DU CHANGEMENT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (4,'lucette.delcombel@intradef.gouv.fr','Communication Management Cat B');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (5,'pierrette.adeux-planchard@intradef.gouv.fr','Conduire et accompagner un projet de changement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (6,'pierrette.adeux-planchard@intradef.gouv.fr','Mobiliser son équipe par la communication');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (7,'veronique.pamart@intradef.gouv.fr','Management et cohésion d''équipe');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (8,'germaine.minker@intradef.gouv.fr','MANAGEMENT ET COHESION D EQUIPE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (9,'olivier.camjouan@intradef.gouv.fr','FONDAMENTAUX CONTENTIEUX ADMIINISTRATIF');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (10,'roseline.gassner@intradef.gouv.fr','Les marchés de formation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (11,'roseline.gassner@intradef.gouv.fr','Rédaction de conventions ou protocoles');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (12,'francoise.chaynes@intradef.gouv.fr','CYCLE SUPERIEUR DE MANAGEMENT GENERAL');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (13,'coralie.duneau@intradef.gouv.fr','EXCEL - tableau de bord');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (14,'coralie.duneau@intradef.gouv.fr','Améliorer sa gestion du temps');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (15,'coralie.duneau@intradef.gouv.fr','POWERPOINT 2010 niveau 1');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (16,'michael.godefroy@intradef.gouv.fr','CYCLE SUPERIEUR DE MANAGEMENT GENERAL');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (17,'marie-eve.mariou@intradef.gouv.fr','POWERPOINT 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (18,'marie-eve.mariou@intradef.gouv.fr','ECRIRE COMME UN JOURNALISTE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (19,'marie-eve.mariou@intradef.gouv.fr','Savoir synthétiser un dossier');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (20,'mireille.millard@intradef.gouv.fr','Management des cadres intermédiaires');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (21,'mireille.millard@intradef.gouv.fr','Communication Management Cat A');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (22,'anne-lise.juguet@intradef.gouv.fr','Gestion de conflits');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (23,'martine.romain@intradef.gouv.fr','Management et cohésion d''équipe');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (24,'martine.romain@intradef.gouv.fr','DROIT SYNDICAL ET DIALOGUE SOCIAL');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (25,'sylvie.diolez@intradef.gouv.fr','DROIT SYNDICAL ET DIALOGUE SOCIAL');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (26,'virginie.codou@intradef.gouv.fr','Initiation à la qualite');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (27,'aline.taboni@intradef.gouv.fr','Initiation à la qualite');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (28,'stephanie.labeyrie@intradef.gouv.fr','Mener un entretien de recrutement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (29,'isabelle.zielinski@intradef.gouv.fr','préparation à l''oral : aller à l''éssentiel');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (30,'isabelle.zielinski@intradef.gouv.fr','Renseigner son dossier RAEP');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (31,'anne.bobtchev@intradef.gouv.fr','ALLIANCE - Ga - Paie');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (32,'ghyslaine.ruperti@intradef.gouv.fr','Formation primes et indemnités accessoires des professeurs');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (33,'ghyslaine.ruperti@intradef.gouv.fr','Cursus des gestionnaire RH module contractuels');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (34,'ghyslaine.ruperti@intradef.gouv.fr','Gestion des RH');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (35,'brigitte.sigalas@intradef.gouv.fr','ORGANISATION DU MINISTERE DE LA DEFENSE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (36,'karine.chiasson@intradef.gouv.fr','OUTILS ET METHODES DE LA GPEEC DANS LA FONCTION PUBLIQUE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (37,'karine.chiasson@intradef.gouv.fr','ETRE MANAGER POUR PREMIERE FOIS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (38,'brigitte.sigalas@intradef.gouv.fr','ALLIANCE - RESPONSABLE EN LECTURE SEULE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (39,'karine.langibout@intradef.gouv.fr','note administrative');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (40,'brigitte.waloszek@intradef.gouv.fr','Management et cohésion d''équipe');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (41,'annie.copinet@intradef.gouv.fr','Excel 10. Tableaux de bord');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (42,'thierry.bollenot@intradef.gouv.fr','Conduite de projets (CFMD)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (43,'marie-francoise.duclos@intradef.gouv.fr','Performances qualité : indicateurs / tableaux de bord');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (44,'marie-francoise.duclos@intradef.gouv.fr','audit interne');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (45,'brigitte.sigalas@intradef.gouv.fr','CONDUITE DE PROJET');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (46,'karima.krim@intradef.gouv.fr','Communication Management Cat B');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (47,'pascale.deschamps-de-paillette@intradef.gouv.fr','E LEARLING CIC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (48,'denis.theobald@intradef.gouv.fr','excel 2010 Base de données et tableaux croisés dynamiques');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (49,'stephane.mabire@intradef.gouv.fr','NOTE ADMINISTRATIVE - PREPARATION AUX CONCOURS/EXAMENS (formation interne)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (50,'stephane.mabire@intradef.gouv.fr','CONDUITE DE PROJET');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (51,'lionel.laffont@intradef.gouv.fr','Mettre en valeur ses compétences et potentiel');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (52,'claudine.berne@intradef.gouv.fr','CommunicationManagement  Cat B');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (53,'claudine.berne@intradef.gouv.fr','Powerpoint initiation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (54,'nathalie.artaud@intradef.gouv.fr','Gestion prévisionnelle des ressources humaines');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (55,'sophie.colonna@intradef.gouv.fr','Améliorer ses relations par l''assertivité');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (56,'sophie.colonna@intradef.gouv.fr','excel 2010 intermédiaire');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (57,'michele.ballevre@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (58,'michele.ballevre@intradef.gouv.fr','FORMATION SCENARIO');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (59,'linda.bondu@intradef.gouv.fr','améliorer ses relations par assertivité');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (60,'linda.bondu@intradef.gouv.fr','gestion des émotions');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (61,'marie-christine.chapon@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (62,'sebastien.cerveau@intradef.gouv.fr','cursus responsable des ressources humaines');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (63,'josyane.darmaillacq@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (64,'rose-marie.le-villo@intradef.gouv.fr','CAP - avancement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (65,'christine.regnier@intradef.gouv.fr','Gestion du stress');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (66,'christine.regnier@intradef.gouv.fr','Améliorer sa gestion du temps');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (67,'delphine.vanheuverzwyn@intradef.gouv.fr','lecture rapide et efficace');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (68,'delphine.vanheuverzwyn@intradef.gouv.fr','ALLIANCE - module "expertise" du synoptique, notamment OE2, OE3, contrôle de supervision, contrôle a posteriori');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (69,'lara.pecciarini@intradef.gouv.fr','les fondamentaux du contentieux administratif');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (70,'helene.petit@intradef.gouv.fr','Actualités et organisation du ministère de la défense');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (71,'ingrid.gaudin@intradef.gouv.fr','L''ECOUTE DANS LA RELATION DE SOUTIEN AU COEUR DE NOS RELATIONS DE TRAVAIL');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (73,'florence.fabre@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (74,'florence.fabre@intradef.gouv.fr','formation métier paie réalisée par le CERH-PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (75,'helene.petit@intradef.gouv.fr','ALLIANCE - RESPONSABLE EN LECTURE SEULE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (76,'jacqueline.gouessant@intradef.gouv.fr','Techniques d''entretiens difficiles');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (77,'jacqueline.gouessant@intradef.gouv.fr','Conduites de projet');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (78,'marie-pierre.marsella@intradef.gouv.fr','MANAGEMENT RESPONSABLE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (79,'laetitia.loron@intradef.gouv.fr','Parcours de commandement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (80,'philippe1.lafon@intradef.gouv.fr','DROIT DES CONCOURS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (81,'francoise.laher@intradef.gouv.fr','ALLIANCE - GESTION ADMINISTRATIVE DES AGENTS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (82,'francoise.laher@intradef.gouv.fr','ALLIANCE - GESTION DES EMPLOIS ET DES COMPETENCES');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (83,'francoise.laher@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (84,'francoise.laher@intradef.gouv.fr','MANAGEMENT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (85,'isabelle.henwood@intradef.gouv.fr','AMELIORER LES SYNERGIES ENTRE LES GENERATIONS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (86,'caroline.sobol@intradef.gouv.fr','E0		parcours cadres confirmés');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (87,'gregoire.despres@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (88,'thierry.dornberger@intradef.gouv.fr','REGLEMENTATION DES CONCOURS PERFECTIONNEMENT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (89,'vincent.minvielle@intradef.gouv.fr','Améliorer ses relations par l''assertivité');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (90,'vincent.minvielle@intradef.gouv.fr','GESTION DES CONFLITS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (91,'nathalie.ponroy@intradef.gouv.fr','Techniques d''entretien difficile membres des AMR');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (92,'nathalie.ponroy@intradef.gouv.fr','RISQUES PSYCHOSOCIAUX');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (93,'virginie.maricau@intradef.gouv.fr','excel 2010 - initiation macro');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (94,'fabienne.cosnefroy@intradef.gouv.fr','PARCOURS CADRES CONFIRMES');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (95,'corinne.sauvat@intradef.gouv.fr','AMELIORER SES RELATIONS PAR L''ASSERTIVITE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (96,'armelle1.friconnet@intradef.gouv.fr','Etre tuteur');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (97,'nathalie.rapaud@intradef.gouv.fr','SENSIBILISATION AUX ACHATS PUBLICS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (98,'isabelle.pleynet@intradef.gouv.fr','Améliorer sa communication');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (99,'florence.jarque@intradef.gouv.fr','Les outils et méthodes de la GPEEC dans la fonction publique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (100,'isabelle.herpin@intradef.gouv.fr','réglementation des concours');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (101,'isabelle.herpin@intradef.gouv.fr','réglementation relative à la mobilité, et aux restructurations');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (102,'maiden.dubois@intradef.gouv.fr','La réforme des marchés publics');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (103,'maiden.dubois@intradef.gouv.fr','Les marchés de formation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (104,'maiden.dubois@intradef.gouv.fr','Améliorer ses relations par l''assertivité');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (105,'alain.artaud@intradef.gouv.fr','Formation statutaire des attachés (CFD)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (106,'veronique.meriaux@intradef.gouv.fr','EXCEL 2010 - Niveau 1 Initiation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (107,'coralie.besse@intradef.gouv.fr','savoir gérer ses émotions');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (108,'coralie.besse@intradef.gouv.fr','améliorer sa communication');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (109,'catherine.astier@intradef.gouv.fr','Formation Outil Alliance (modules GA et paie)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (110,'catherine.astier@intradef.gouv.fr','Alliance Requêteur BO');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (111,'joseph.tibource@intradef.gouv.fr','Business Object perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (112,'joseph.tibource@intradef.gouv.fr','Piloter la gestion prévisionnelle des RH');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (113,'isabelle.tipaka@intradef.gouv.fr','Formation sur le handicap psychique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (114,'guylaine.raud@intradef.gouv.fr','EXCEL 2010 Niv 2 Intermédiaire');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (115,'veronique.lebrun@intradef.gouv.fr','cursus formation au SIFE chorus MP7');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (116,'veronique.lebrun@intradef.gouv.fr','Performances qualité : indicateurs / tableaux de bord');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (117,'veronique.lebrun@intradef.gouv.fr','LES NOUVELLES RÈGLES DE LA COMPTABILITÉ PUBLIQUE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (118,'francine.naudais@intradef.gouv.fr','formation à la gestion des risques psycho sociaux');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (119,'alexandra.bayer@intradef.gouv.fr','Management des cadres intermédiaires');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (120,'dominique.vidal@intradef.gouv.fr','Management et cohésion d''équipe');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (121,'michel.frisan@intradef.gouv.fr','Cursus formation SIFE CHORUS Restitutions MP 7');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (122,'marie-claire.moysan@intradef.gouv.fr','FONDAMENTAUX CONTENTIEUX ADMIINISTRATIF');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (123,'agnes.harvey@intradef.gouv.fr','Les outils et méthodes de la GPEEC dans la fonction publique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (124,'laurent.trottet@intradef.gouv.fr','conduire un entretien de recrutement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (125,'geraldine.schneider@intradef.gouv.fr','FORMATION ALLIANCE + requêteur');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (126,'geraldine.schneider@intradef.gouv.fr','FORMATION REGLEMENTATION DISCIPLINE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (127,'geraldine.schneider@intradef.gouv.fr','FORMATION Ouvrier de l''Etat');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (128,'benoit.tourment@intradef.gouv.fr','Plan de communication (Poposition : ISCPA Lyon, 3 jours)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (129,'benoit.tourment@intradef.gouv.fr','Formation personnalisée POWERPOINT 2010 e-Learning');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (130,'chantal.jean@intradef.gouv.fr','Formation reglementation concours perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (131,'noel.de-la-pomelie@intradef.gouv.fr','sources de droit et introduction à la légistique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (132,'noel.de-la-pomelie@intradef.gouv.fr','légistique niveau intermédiaire');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (133,'frantz.dollin@intradef.gouv.fr','Légistique niveau perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (134,'patrick.nogue@intradef.gouv.fr','SANS OBJET : DEPART RETRAITE LE 01/05/2017');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (135,'caroline.pittet@intradef.gouv.fr','CONDUITE DE PROJET');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (136,'blandine.le-bris@intradef.gouv.fr','Le manager métier et les SIC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (137,'sylvette.ordureau@intradef.gouv.fr','La gestion des conflits');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (139,'evelyne.made@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (140,'evelyne.made@intradef.gouv.fr','Management et cohésion d''équipe');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (141,'arthur.beaulieu@intradef.gouv.fr','Coaching en vue de développer son potentiel');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (142,'virginie.fouquet@intradef.gouv.fr','Sharepoint 2013 Utilisation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (143,'virginie.fouquet@intradef.gouv.fr','Mener un entretien de recrutement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (144,'yves.gruson@intradef.gouv.fr','Note Administrative - Préparation aux Concours & Examens (formation interne)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (145,'yves.gruson@intradef.gouv.fr','Statut des fonctionnaires de l''Etat');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (146,'maryline.alcaina@intradef.gouv.fr','PREPARER SA RETRAITE (3 jours)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (147,'maryline.alcaina@intradef.gouv.fr','PREPARER SA RETRAITE (0.5 jour)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (148,'monique.magadoux@intradef.gouv.fr','SANS OBJET : DEPART A LA RETRAITE 2017');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (149,'frederic.boyon@intradef.gouv.fr','Management et cohésion d''équipe');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (150,'elodie1.gendry@intradef.gouv.fr','Préparation aux concours de catégorie A');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (151,'elodie1.gendry@intradef.gouv.fr','NOTE ADMINISTRATIVE PREPARATION AUX CONCOURS/EXAMENS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (152,'david.del-peso@intradef.gouv.fr','INITIATION GESTION PREVISIONNELLE  EMPLOIS ET COMPETENCES  (GPEEC) INTERNE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (153,'emmanuelle.laquit@intradef.gouv.fr','INTELLIGENCE ECONOMIQUE NOTIONS DE BASE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (154,'valerie.lasbarreres-candau@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (155,'valerie.lasbarreres-candau@intradef.gouv.fr','La prise de notes et le compte-rendu de réunion');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (156,'valerie.lasbarreres-candau@intradef.gouv.fr','Formation personnalisée OUTLOOK 2010 e-Learning');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (157,'emmanuel.helluin@intradef.gouv.fr','Comprendre et appliquer les exigences ISO 9001');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (158,'evelyne.made@intradef.gouv.fr','Requêtes sous BO');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (159,'marie-helene.damblade@intradef.gouv.fr','-	Consulter un dossier RAEP, présenter son parcours à l’oral');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (160,'marie-helene.damblade@intradef.gouv.fr','Etre manager pour la 1ère fois');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (161,'franck.chevreux@intradef.gouv.fr','Manager les processus');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (162,'franck.chevreux@intradef.gouv.fr','Gestion du temps, stress et délégation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (163,'isabelle.zielinski@intradef.gouv.fr','Cursus RH certifiant - Gestion du personnel fonctionnaire E-learning');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (164,'isabelle.zielinski@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (165,'carole.routard@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (166,'carole.routard@intradef.gouv.fr','MANAGEMENT TRANSVERSAL');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (167,'amira.belbachir@intradef.gouv.fr','conduire un projet de certification ISO 9001');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (168,'amira.belbachir@intradef.gouv.fr','formation à la déontologie');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (169,'amira.belbachir@intradef.gouv.fr','actualité du droit public');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (170,'david.del-peso@intradef.gouv.fr','Les outils et méthodes de la GPEEC dans la fonction publique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (171,'elie.le-cam@intradef.gouv.fr','PARCOURS JEUNES MANAGERS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (172,'elie.le-cam@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (173,'mireille.guehl@intradef.gouv.fr','La responsabilité civile, pénale, administrative et disciplinaire des fonctionnaires');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (174,'mireille.guehl@intradef.gouv.fr','La gestion des personnels en situation de handicap');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (175,'agnes.moussinat@intradef.gouv.fr','LECTURE RAPIDE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (176,'sabine.melin@intradef.gouv.fr','Gestion et administration des fonctionnaires');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (177,'checkousmane.gaffar@intradef.gouv.fr','cycle certifiant en informatique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (178,'checkousmane.gaffar@intradef.gouv.fr','Réseaux informatiques pour non informaticiens');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (179,'julie.perilleau@intradef.gouv.fr','EXCEL 2010 - Niveau 1 Initiation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (180,'etienne1.caillat@intradef.gouv.fr','gestion des agents contractuels');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (181,'etienne1.caillat@intradef.gouv.fr','culture défense');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (182,'dominique.turelli@intradef.gouv.fr','Communication Management Cat B');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (183,'dominique.turelli@intradef.gouv.fr','Améliorer son leadership');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (184,'daniele.tolu@intradef.gouv.fr','Connaissance des différents statuts des personnels civils du MINDEF');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (185,'marie-christine.grassi@intradef.gouv.fr','POWERPOINT 2010 - Niveau 1 initiation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (186,'marie-christine.grassi@intradef.gouv.fr','POWERPOINT 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (187,'marie-christine.grassi@intradef.gouv.fr','Communication niveau 3');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (188,'marie-christine.grassi@intradef.gouv.fr','ECRIRE POUR LE WEB');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (189,'caroline.masson@intradef.gouv.fr','Actualités juridiques et management de la qualité du droit (CFMD)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (190,'emmanuel.helluin@intradef.gouv.fr','Formations GAPaie délivrées par le CERHPC niveau Maîtrise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (191,'emmanuel.helluin@intradef.gouv.fr','Formations GAPaie délivrées par le CERHPC niveau Expertise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (192,'annie.nicol@intradef.gouv.fr','Formation de formateurs');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (193,'sylvie.perrin@intradef.gouv.fr','Formations GAPaie délivrées par le CERHPC niveaux Maitrise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (194,'sylvie.perrin@intradef.gouv.fr','Formations GAPaie délivrées par le CERHPC niveaux Expertise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (195,'ousmane.aoudou@intradef.gouv.fr','Formations GAP délivrées par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (196,'ousmane.aoudou@intradef.gouv.fr','Formations GAP délivrées par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (197,'ousmane.aoudou@intradef.gouv.fr','Formations GAP délivrées par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (198,'nicolas.gonon@intradef.gouv.fr','Formations GAP délivrées par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (199,'nicolas.gonon@intradef.gouv.fr','Formations GAP délivrées par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (200,'nicolas.gonon@intradef.gouv.fr','Formations GAP délivrées par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (201,'cecile.roquefort@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (202,'cecile.roquefort@intradef.gouv.fr','ALLIANCE - RESPONSABLE EN LECTURE SEULE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (203,'isabelle.lehuede@intradef.gouv.fr','Formations GAP délivrées par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (204,'isabelle.lehuede@intradef.gouv.fr','Formations GAP délivrées par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (205,'maryvette.meslin@intradef.gouv.fr','Améliorer ses écrits professionnels');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (206,'dominique.dongard@intradef.gouv.fr','Animer une équipe');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (207,'dominique.dongard@intradef.gouv.fr','Participation et conduite de réunion Cat B et C');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (208,'dominique.dongard@intradef.gouv.fr','Mettre en valeur ses compétences et potentiel');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (209,'renaud.lavoissiere@intradef.gouv.fr','MANAGER LES PROCESSUS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (210,'renaud.lavoissiere@intradef.gouv.fr','LE PILOTAGE DE LA MASSE SALARIALE - INTERNE DEFENSE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (211,'martine.lecoeur@intradef.gouv.fr','Formation GAP délivrées par CERH-PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (212,'martine.lecoeur@intradef.gouv.fr','Formation GAP délivrées par CERH-PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (213,'magali.bellot@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (214,'julien.chesnel@intradef.gouv.fr','Améliorer ses écrits professionnels');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (215,'sabine.melin@intradef.gouv.fr','Formations GAPaie délivrée par le CERH PC niveau Maîtrise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (216,'sabine.melin@intradef.gouv.fr','Formations GAPaie délivrée par le CERH PC niveau Expertise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (217,'monique.lampasona@intradef.gouv.fr','Formations GAPaie dispensées par le CERHPC niveau Expertise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (218,'fabienne.berthaud@intradef.gouv.fr','Formations dispensées par le CERHPC niveau Application');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (219,'fabienne.berthaud@intradef.gouv.fr','Formations dispensées par le CERHPC niveau Maîtrise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (220,'fabienne.berthaud@intradef.gouv.fr','Formations dispensées par le CERHPC niveau Expertise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (221,'julien.chesnel@intradef.gouv.fr','savoir calculer les rémunérations nettes maintenues dans le cadre de l''application de la jurisprudence GRIMLER');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (222,'thierry.severin@intradef.gouv.fr','Formation GAPaie délivrée par le CERHPC Niveau Maîtrise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (223,'thierry.severin@intradef.gouv.fr','Formation GAPaie délivrée par le CERHPC Niveau Expertise');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (225,'caroline.clement@intradef.gouv.fr','Prise de parole en public');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (226,'nelly.siviere@intradef.gouv.fr','Améliorer sa gestion du temps');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (227,'christophe1.martins@intradef.gouv.fr','savoir calculer les rémunérations nettes maintenues dans le cadre de l''application de la jurisprudence GRIMLER');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (228,'arlette.bissieres@intradef.gouv.fr','Formation qualifiante d?ouvrier de prévention HCA');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (229,'arlette.bissieres@intradef.gouv.fr','Formation GA PAIE délivrée par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (230,'arlette.bissieres@intradef.gouv.fr','Formation GA PAIE délivrée par le CERH PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (231,'etienne.jacquel@intradef.gouv.fr','Enjeux de la modernisation de la fonction publique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (232,'etienne.jacquel@intradef.gouv.fr','Pilotage de la masse salariale (interne défense)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (233,'sandrine.husson@intradef.gouv.fr','Fondamentaux des ressources humaines (CFMD)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (234,'sandrine.husson@intradef.gouv.fr','Formation des formateurs');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (235,'karine2.martin@intradef.gouv.fr','Participation et conduite de réunion Cat B et C');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (236,'karine2.martin@intradef.gouv.fr','Mettre en valeur ses compétences et potentiel');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (237,'frantz-eric.leloup@intradef.gouv.fr','Enjeux et modernisation de la fonction publique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (238,'frantz-eric.leloup@intradef.gouv.fr','L''actualité de la commande publique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (239,'suzy.flainville@intradef.gouv.fr','Les clefs de la communication managériale');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (240,'suzy.flainville@intradef.gouv.fr','la responsabilité civile, pénale et administrative des fonctionnaires');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (241,'suzy.flainville@intradef.gouv.fr','Tableaux de bord RH');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (242,'agnes.chaine-rommel@intradef.gouv.fr','Formations GAP délivrées par CERH-PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (243,'agnes.chaine-rommel@intradef.gouv.fr','Formations GAP délivrées par CERH-PC');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (244,'gwenhael.cudennec@intradef.gouv.fr','ECOUTE ACTIVE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (245,'murielle.maho@intradef.gouv.fr','Aide à la décision et au pilotage');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (246,'sylvie.mahe-guerin@intradef.gouv.fr','EXCEL 2010 - Tableaux de bord');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (247,'christelle.richer@intradef.gouv.fr','Mener un entretien de recrutement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (248,'christelle.richer@intradef.gouv.fr','EXCEL 2010 - Tableaux de bord');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (249,'christelle.richer@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (250,'nadine.pitois@intradef.gouv.fr','formation à l''examen pro SACS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (251,'nadine.pitois@intradef.gouv.fr','FORMATION AU RAEP');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (252,'axel.beugniot@intradef.gouv.fr','Contentieux administratif initiation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (253,'axel.beugniot@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (254,'marianne.nabaloum@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (256,'maryvette.meslin@intradef.gouv.fr','savoir calculer les rémunérations nettes maintenues dans le cadre de l''application de la jurisprudence GRIMLER');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (257,'laurent.valy@intradef.gouv.fr','Droit administratif perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (258,'laurent.valy@intradef.gouv.fr','Comprendre un texte juridique');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (259,'lynda.wos@intradef.gouv.fr','Excel 10 - introduction aux macros.');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (260,'christelle.bonnet@intradef.gouv.fr','CHORUS Programmation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (261,'reine.sanchez@intradef.gouv.fr','CONDUIRE UN ENTRETIEN DE RECRUTEMENT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (262,'reine.sanchez@intradef.gouv.fr','POWERPOINT 2010 - Niveau 1 initiation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (263,'alain.fong-yam-soy@intradef.gouv.fr','lecture efficace d''écrits professionnels');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (265,'francoise.sachot@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement (formation externe)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (266,'francoise.sachot@intradef.gouv.fr','EXCEL 2010 - base de donnée et tableaux croisés dynamiques (formation interne)');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (267,'francoise.sachot@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (268,'jean-francois.orhan@intradef.gouv.fr','Outlook 2010');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (269,'marie-france.pichereau@intradef.gouv.fr','GESTION DES RESSOURCES HUMAINES PAR LA MASSE SALARIALE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (270,'marie-france.pichereau@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (271,'marie-france.pichereau@intradef.gouv.fr','GESTION PREVISIONNELLE DES RESSOURCES HUMAINES');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (272,'martine.gomez@intradef.gouv.fr','ALLIANCE REQUETE BUSINESS OBJECT');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (273,'virginie.boursier@intradef.gouv.fr','PARCOURS JEUNES MANAGERS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (274,'virginie.boursier@intradef.gouv.fr','EXCEL 2010 - Tableaux de bord');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (275,'marion.dymel@intradef.gouv.fr','PARCOURS JEUNES MANAGERS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (276,'marion.dymel@intradef.gouv.fr','Pilotage de la masse salariale et des emplois');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (277,'gwenhael.cudennec@intradef.gouv.fr','ANALYSE DES EMPLOIS ET DES EFFECTIFS');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (278,'david.cadouel@intradef.gouv.fr','GESTION TEMPS, STRESS ET DELEGATION');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (279,'francois.demets@intradef.gouv.fr','GESTION PREVISIONNELLE DES RESSOURCES HUMAINES');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (280,'dominique.couloigner@intradef.gouv.fr','tableau de bord RH');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (281,'dominique.couloigner@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (282,'albane.sauton@intradef.gouv.fr','EXCEL 2010 - Niveau 1 Initiation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (283,'albane.sauton@intradef.gouv.fr','lecture rapide');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (284,'alain.fong-yam-soy@intradef.gouv.fr','Constituer Constituer dossier de validation d''expérience acquis de l''expérience VAE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (285,'isabelle.zielinski@intradef.gouv.fr','préparation à l''oral : aller à l''éssentiel');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (286,'isabelle.zielinski@intradef.gouv.fr','Renseigner son dossier RAEP');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (287,'isabelle.zielinski@intradef.gouv.fr','Cursus RH certifiant - Gestion du personnel fonctionnaire E-learning');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (288,'isabelle.zielinski@intradef.gouv.fr','EXCEL 2010 - Niveau 3 Perfectionnement');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (289,'eliane.besnard@intradef.gouv.fr','SANS OBJET - DEPART RETRAITE');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (290,'martine.subirana@intradef.gouv.fr','EXCEL 2010 - Niveau 1 Initiation');
Insert into FORMATION_DEMANDEE_ADMIN_2016 ("ID","EMAIL","LIBELLE") values (291,'martine.subirana@intradef.gouv.fr','Tableau de bord RH');
commit;
exit;
