REM INSERTING into FORMATION_DEMANDEE_AGENT_2016
SET DEFINE OFF;
SET SQLBLANKLINES ON;
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (1,'catherine.gueroult@intradef.gouv.fr','POWERPOINT 2010 - Niveau 1 initiation');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (2,'catherine.gueroult@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (3,'coralie.duneau@intradef.gouv.fr','Les marchés de formation');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (4,'coralie.duneau@intradef.gouv.fr','POWERPOINT 2010 niveau 2');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (5,'coralie.duneau@intradef.gouv.fr','RÉGLEMENTATION DES MARCHÉS PUBLICS');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (7,'anne-lise.juguet@intradef.gouv.fr','Tour extérieur d''administrateur civil');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (8,'anne-lise.juguet@intradef.gouv.fr','CONDUITE DE PROJETS');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (9,'lucette.delcombel@intradef.gouv.fr','Initiation au processus communication');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (10,'sylvie.diolez@intradef.gouv.fr','préparation à la retraite');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (11,'virginie.codou@intradef.gouv.fr','formation des formateurs');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (12,'virginie.codou@intradef.gouv.fr','prise de parole en public');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (13,'stephanie.labeyrie@intradef.gouv.fr','Préparation par correspondance au concours cat A - Attaché d''administration');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (14,'marie-francoise.duclos@intradef.gouv.fr','EXCEL 2010 - Tableaux de bord');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (15,'maryse.nicod@intradef.gouv.fr','Anglais intensif niveau intermediate');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (16,'delphine.barbosa@intradef.gouv.fr','Rédaction administrative (courriers administratifs)');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (17,'denis.theobald@intradef.gouv.fr','WORD 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (18,'claudine.berne@intradef.gouv.fr','Initation au process com');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (19,'frederique.lusseau@intradef.gouv.fr','Anglais intensif niveau intermediate');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (20,'jacqueline.gouessant@intradef.gouv.fr','Conseil en Evolution Professionnelle');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (21,'laetitia.loron@intradef.gouv.fr','Excel');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (22,'philippe1.lafon@intradef.gouv.fr','EXCEL 2010 - Niveau 1 Initiation');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (23,'isabelle.henwood@intradef.gouv.fr','CREER DES MODULES EN E-LEARNING');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (24,'caroline.sobol@intradef.gouv.fr','E0		E 0 conduite du changement');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (25,'caroline.sobol@intradef.gouv.fr','E 0 gestion du temps stress et délégation');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (26,'vincent.minvielle@intradef.gouv.fr','Renseigner son dossier RAEP');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (27,'laurent.lemoine@intradef.gouv.fr','Outlook 2010');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (28,'marilyse.dupont@intradef.gouv.fr','Préparation à la retraite');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (29,'corinne.sauvat@intradef.gouv.fr','MANAGER PAR LE THEATRE');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (30,'corinne.sauvat@intradef.gouv.fr','ANGLAIS INITIATION');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (31,'christiane.massicot@intradef.gouv.fr','Formation personnalisée OUTLOOK 2010 e-Learning');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (32,'christiane.massicot@intradef.gouv.fr','processus de communication');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (33,'isabelle.pleynet@intradef.gouv.fr','WORD 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (34,'maiden.dubois@intradef.gouv.fr','Renseigner son dossier RAEP');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (35,'coralie.besse@intradef.gouv.fr','formation en développement personnel et bien-être de la personne, art thérapie et musicothérapie');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (36,'catherine.astier@intradef.gouv.fr','Sensibilisation au contrôle interne');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (37,'laurent.trottet@intradef.gouv.fr','Parcours cadre confirmé');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (38,'benoit.tourment@intradef.gouv.fr','Le contentieux dans les marchés publics');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (39,'noel.de-la-pomelie@intradef.gouv.fr','la gestion des contractuels');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (40,'frantz.dollin@intradef.gouv.fr','Contentieux administratif initiation');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (41,'frantz.dollin@intradef.gouv.fr','Management et cohésion d''équipe');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (42,'frantz.dollin@intradef.gouv.fr','Anglais extensif collectif');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (43,'sylvette.ordureau@intradef.gouv.fr','SENSIBILISATION AUX ACHATS PUBLICS');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (44,'sylvette.ordureau@intradef.gouv.fr','Sensibilisation à la négociation de l''achat');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (45,'evelyne.made@intradef.gouv.fr','préparation à l''examen professionnel SACS');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (46,'chantal.duluc@intradef.gouv.fr','Préparation à la retraite');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (47,'karine.chiasson@intradef.gouv.fr','Formation CMC');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (48,'karine.chiasson@intradef.gouv.fr','Piloter la GPRH');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (49,'valerie.lasbarreres-candau@intradef.gouv.fr','Formation personnalisée EXCEL 2010 e-Learning');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (50,'carole.routard@intradef.gouv.fr','DROIT DU TRAVAIL');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (51,'carole.routard@intradef.gouv.fr','COMPRENDRE UN TEXTE JURIDIQUE');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (52,'david.del-peso@intradef.gouv.fr','formation SOLON');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (53,'isaure.lewenberg-sturm@intradef.gouv.fr','POWER POINTPOWERPOINT 2010  Niveau 1 initiation');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (54,'isaure.lewenberg-sturm@intradef.gouv.fr','Utilisation de l''application OMSAR 2');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (56,'mireille.guehl@intradef.gouv.fr','Contentieux administratif - initiation');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (57,'agnes.moussinat@intradef.gouv.fr','Améliorer ses relations par l''assertivité');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (58,'checkousmane.gaffar@intradef.gouv.fr','Développement de sites Web - Pratique');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (59,'julie.perilleau@intradef.gouv.fr','ETRE MANAGER POUR LA 1ERE FOIS');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (60,'julie.perilleau@intradef.gouv.fr','BILAN DE COMPETENCES');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (61,'carole.eraud@intradef.gouv.fr','Préparation au concours des IRA');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (62,'etienne1.caillat@intradef.gouv.fr','note administrative - préparation concours - formation interne');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (63,'etienne1.caillat@intradef.gouv.fr','droit administratif initiation');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (64,'caroline.masson@intradef.gouv.fr','Retraites (La Rochelle)');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (65,'annie.nicol@intradef.gouv.fr','Renseigner son dossier RAEP');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (66,'renaud.lavoissiere@intradef.gouv.fr','LA PRATIQUE DE LA PAYE AU SEIN DE LA FONCTION PUBLIQUE  DE L''ETAT');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (67,'renaud.lavoissiere@intradef.gouv.fr','CONSTITUER UN DOSSIER RECONNAISSANCE ACQUIS EXPERIENCE PRO (RAEP) ET SAVOIR PRESENTER SON PARCOURS A L''ORAL');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (69,'elodie1.gendry@intradef.gouv.fr','CURSUS CONSEILLER MOBILITE CARRIERE');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (70,'elodie1.gendry@intradef.gouv.fr','INTELLIGENCE ECONOMIQUE NOTIONS DE BASE');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (71,'dominique.turelli@intradef.gouv.fr','Mieux appréhender le changement dans sa vie professionnelle');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (72,'dominique.turelli@intradef.gouv.fr','EXCEL 2010 - Niveau 2 Intermédiaire');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (73,'julien.chesnel@intradef.gouv.fr','ANALYSE DE TEXTE : ANALYSE, COMPREHENSION ET REFORMULATION');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (74,'blandine.le-bris@intradef.gouv.fr','Améliorer ses relations par l''assertivité');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (75,'caroline.pittet@intradef.gouv.fr','Pilotage de la masse salariale et des emplois');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (76,'caroline.pittet@intradef.gouv.fr','Actualité du droit public');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (77,'brigitte.sigalas@intradef.gouv.fr','Affirmation de soi');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (78,'nelly.siviere@intradef.gouv.fr','Savoir synthétiser un dossier');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (79,'christophe1.martins@intradef.gouv.fr','Renseigner son dossier RAEP (EXAMEN PRO SACE)');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (80,'elie.le-cam@intradef.gouv.fr','ETRE MANAGER POUR LA 1ERE FOIS');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (81,'elie.le-cam@intradef.gouv.fr','MANAGEMENT TRANSVERSAL');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (82,'karine2.martin@intradef.gouv.fr','formation au RAEP dans le cadre des concours de catégorie A');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (83,'karine2.martin@intradef.gouv.fr','Préparation aux IRA');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (84,'eliane.besnard@intradef.gouv.fr','SANS OBJET - DEPART RETRAITE');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (85,'suzy.flainville@intradef.gouv.fr','Constituer un dossier RAEP, présenter son parcours à l''oral (APAE)');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (86,'emmanuelle.laquit@intradef.gouv.fr','intelligence économique et veille stratégique');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (87,'emmanuelle.laquit@intradef.gouv.fr','Conduite de réunion Niveaux A et B');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (88,'christelle.richer@intradef.gouv.fr','WORD 2010 - Niveau 2 Perfectionnement');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (93,'murielle.maho@intradef.gouv.fr','Excel 2010 VBA');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (95,'nadine.pitois@intradef.gouv.fr','Formation aux évolutions des métiers de la paye');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (96,'axel.beugniot@intradef.gouv.fr','DROIT SYNDICAL ET DIALOGUE SOCIAL');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (97,'christelle.bonnet@intradef.gouv.fr','Note administrative - Préparation concours et examens');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (98,'isabelle.filbien@intradef.gouv.fr','ANGLAIS COLLECTIF');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (99,'marion.dymel@intradef.gouv.fr','ENJEUX ET PERSPECTIVES DES FINANCES PUBLIQUES DE L ETAT');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (100,'francois.demets@intradef.gouv.fr','PARCOURS JEUNES MANAGERS');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (101,'virginie.boursier@intradef.gouv.fr','Statuts des fonctionnaires de l''Etat');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (102,'dominique.couloigner@intradef.gouv.fr','Le système d''archivage électronique');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (103,'dominique.couloigner@intradef.gouv.fr','Rédaction de textes normatifs');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (104,'marianne.nabaloum@intradef.gouv.fr','Cursus responsable resssources humaines');
Insert into FORMATION_DEMANDEE_AGENT_2016 ("ID","EMAIL","LIBELLE") values (105,'eliane.besnard@intradef.gouv.fr','SANS OBJET - DEPART RETRAITE');
commit;
exit;
