<?php

namespace AppBundle\Repository\CrepRepository\CrepMinefAbcRepository;

/**
 * CrepMinefAbcRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMinefAbcRepository extends \Doctrine\ORM\EntityRepository
{
}
