<?php

namespace AppBundle\Repository\CrepRepository\CrepMinefAbcRepository;

/**
 * CrepMinefAbcCompetenceTransverseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMinefAbcCompetenceTransverseRepository extends \Doctrine\ORM\EntityRepository
{
}
