<?php

namespace AppBundle\Repository\CrepRepository\CrepEddRepository;

/**
 * CrepEddCompetenceTransverseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepEddCompetenceTransverseRepository extends \Doctrine\ORM\EntityRepository
{
}