<?php

namespace AppBundle\Repository\CrepRepository\CrepEddRepository;

/**
 * CrepEddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepEddRepository extends \Doctrine\ORM\EntityRepository
{
}
