<?php
namespace AppBundle\Repository\CrepRepository\CrepEddRepository;

/**
 * CrepEddCompetenceTransverseRequiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepEddCompetenceTransverseRequiseRepository extends \Doctrine\ORM\EntityRepository
{
}
