<?php

namespace AppBundle\Repository\CrepRepository\CrepEddRepository;

/**
 * ObjectifEvalueCollectifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifEvalueCollectifRepository extends \Doctrine\ORM\EntityRepository
{
    
}
