<?php

namespace AppBundle\Repository\CrepRepository\CrepEddRepository;

/**
 * ObjectifEvalueParentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifEvalueParentRepository extends \Doctrine\ORM\EntityRepository
{
}
