#!/bin/bash

HTTP_REP_EXPLOIT_AS=@@HTTP_REP_EXPLOIT_AS@@
HTTP_REP_PRODUIT_AS=@@HTTP_REP_PRODUIT_AS@@
APPLI_PHP_FILE=@@APPLI_PHP_FILE@@
HTTP_NOM_APPLI=@@HTTP_NOM_APPLI@@
APPLI_ENV=@@APPLI_ENV@@


REP_SOURCES="ESTEVE"
FIC_LOG="commandes.log"

REP_LOG="${HTTP_REP_EXPLOIT_AS}/logs"
REP_CONF="${HTTP_REP_PRODUIT_AS}/conf.d/"
COMMANDE_CONSOLE="${HTTP_REP_PRODUIT_AS}/docroot/${REP_SOURCES}/bin/console"
FLAG_LIVRAISON="/tmp/LIVRAISON_${HTTP_NOM_APPLI}_${APPLI_ENV}"

. ~/.bash_profile