<?php

namespace AppBundle\Repository\CrepRepository\CrepMinefContractRepository;

/**
 * CrepMinefContractRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMinefContractRepository extends \Doctrine\ORM\EntityRepository
{
}
