<?php

namespace AppBundle\Repository\CrepRepository\CrepMinefContractRepository;

/**
 * CrepMinefContractCompetenceTransverseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMinefContractCompetenceTransverseRepository extends \Doctrine\ORM\EntityRepository
{
}
