<?php

namespace AppBundle\Repository\CrepRepository\CrepScl02Repository;

/**
 * CrepScl02CompetenceTransverseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepScl02CompetenceTransverseRepository extends \Doctrine\ORM\EntityRepository
{
}
