<?php

namespace AppBundle\Repository\CrepRepository\CrepMso5Repository;

/**
 * CrepMso5ObjectifFuturParentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMso5ObjectifFuturParentRepository extends \Doctrine\ORM\EntityRepository
{
}
