<?php

namespace AppBundle\Repository\CrepRepository\CrepMso5Repository;

/**
 * CrepMso5ObjectifEvalueCollectifRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMso5ObjectifEvalueCollectifRepository extends \Doctrine\ORM\EntityRepository
{
}
