<?php

namespace AppBundle\Repository\CrepRepository\CrepMso5Repository;

/**
 * CrepMso5ObjectifEvalueRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMso5ObjectifEvalueRepository extends \Doctrine\ORM\EntityRepository
{
}