<?php

namespace AppBundle\Repository;

namespace AppBundle\Repository\CrepRepository\CrepMcc02Repository;

/**
 * CrepMcc02CompetenceDemontreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMcc02CompetenceDemontreeRepository extends \Doctrine\ORM\EntityRepository
{
}