<?php

namespace AppBundle\Repository\CrepRepository\CrepMccRepository;

use Doctrine\ORM\EntityRepository;

/**
 * CrepMccRespEncadrementRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMccRespEncadrementRepository extends EntityRepository
{
}
