<?php

namespace AppBundle\Repository\CrepRepository\CrepMccRepository;

/**
 * CrepMccCompetenceTransverseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMccFormationPrepaConcoursRepository extends CrepMccFormationAVenirRepository
{
}
