<?php

namespace AppBundle\Repository\CrepRepository\CrepMccRepository;

/**
 * CrepMccFormationMetierRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMccFormationMetierRepository extends CrepMccFormationAVenirRepository
{
}
