<?php

namespace AppBundle\Repository\CrepRepository\CrepMccRepository;

/**
 * CrepMccFormationDevQualifRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMccFormationDevQualifRepository extends CrepMccFormationAVenirRepository
{
}
