<?php

namespace AppBundle\Repository\CrepRepository\CrepMccRepository;

use Doctrine\ORM\EntityRepository;

/**
 * CrepMccCritereAppreciationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrepMccCritereAppreciationRepository extends EntityRepository
{
}
